// Auto-generated static course data - used as fallback when database is unavailable
// This ensures the app works on Vercel even if the PostgreSQL database is not seeded

export interface StaticCourse {
  id: string; slug: string; title: string; subtitle: string; level: string;
  price: number; compareAtPrice: number | null; description: string; features: string;
  modulesCount: number; lessonsCount: number; estimatedHours: number; imageUrl: string | null; order: number;
}

export interface StaticModule {
  id: string; courseId: string; moduleNumber: number; title: string;
  description: string; icon: string | null; order: number;
}

export interface StaticLesson {
  id: string; moduleId: string; lessonNumber: number; title: string;
  contentType: string; estimatedMinutes: number; order: number;
  videoUrl?: string | null;
}

export const STATIC_COURSES: StaticCourse[] = [
  {
    id: "static-beginner",
    slug: "beginner",
    title: "Beginner English",
    subtitle: "From A1 to A2 \u2014 Build your foundation",
    level: "A1-A2",
    price: 49,
    compareAtPrice: 79,
    description: "Build a solid English foundation from scratch. This comprehensive course takes you from complete beginner to A2 level, covering essential vocabulary, basic grammar, and everyday communication skills. Perfect for those starting their English learning journey.",
    features: "[\"5 comprehensive modules\",\"50 interactive lessons\",\"Grammar fundamentals with exercises\",\"Vocabulary building (500+ words)\",\"Quizzes after every module\",\"Progress tracking dashboard\",\"Completion certificate\"]",
    modulesCount: 5,
    lessonsCount: 50,
    estimatedHours: 30,
    imageUrl: null,
    order: 1,
  },
  {
    id: "static-intermediate",
    slug: "intermediate",
    title: "Intermediate English",
    subtitle: "From B1 to B2 \u2014 Communicate with confidence",
    level: "B1-B2",
    price: 79,
    compareAtPrice: 129,
    description: "Elevate your English to professional and academic levels. Master complex grammar, professional communication, and academic writing. This course bridges the gap between basic English and confident, fluent communication in any context.",
    features: "[\"5 comprehensive modules\",\"50 interactive lessons\",\"Complex grammar mastery\",\"Professional communication skills\",\"Academic English foundations\",\"Quizzes after every module\",\"Progress tracking dashboard\",\"Completion certificate\"]",
    modulesCount: 5,
    lessonsCount: 50,
    estimatedHours: 50,
    imageUrl: null,
    order: 2,
  },
  {
    id: "static-advanced",
    slug: "advanced",
    title: "Advanced English",
    subtitle: "From C1 to C2 \u2014 Master the language",
    level: "C1-C2",
    price: 99,
    compareAtPrice: 169,
    description: "Achieve true English mastery at the highest level. Explore rhetoric, academic publishing, linguistic precision, and cultural intelligence. This course prepares you for C2 proficiency certification and professional excellence in any English-speaking environment.",
    features: "[\"5 comprehensive modules\",\"50 interactive lessons\",\"Academic & professional mastery\",\"Rhetoric & persuasion techniques\",\"Nuanced communication skills\",\"Quizzes after every module\",\"Progress tracking dashboard\",\"Completion certificate\"]",
    modulesCount: 5,
    lessonsCount: 50,
    estimatedHours: 60,
    imageUrl: null,
    order: 3,
  },
];

export const STATIC_MODULES: StaticModule[] = [
  // Beginner modules
  {
    id: "static-beg-m1",
    courseId: "static-beginner",
    moduleNumber: 1,
    title: "Foundations",
    description: "Master the essential building blocks of English: present tenses, articles, prepositions, and basic conversation skills.",
    icon: "HandMetal",
    order: 0,
  },
  {
    id: "static-beg-m2",
    courseId: "static-beginner",
    moduleNumber: 2,
    title: "Everyday Communication",
    description: "Master everyday English for restaurants, shopping, travel, and emergencies with practical phrases and real-world scenarios.",
    icon: "Sun",
    order: 1,
  },
  {
    id: "static-beg-m3",
    courseId: "static-beginner",
    moduleNumber: 3,
    title: "Expanding Skills",
    description: "Expand your English skills with perfect tenses, pronouns, and everyday communication.",
    icon: "Users",
    order: 2,
  },
  {
    id: "static-beg-m4",
    courseId: "static-beginner",
    moduleNumber: 4,
    title: "Practical Communication",
    description: "Apply your English skills to real-world situations: phone calls, travel, health, and social media.",
    icon: "MessageCircle",
    order: 3,
  },
  {
    id: "static-beg-m5",
    courseId: "static-beginner",
    moduleNumber: 5,
    title: "Consolidation",
    description: "Review and consolidate everything you have learned, from tenses to pronunciation, and prepare for the A2 level.",
    icon: "Award",
    order: 4,
  },
  // Intermediate modules
  {
    id: "static-int-m1",
    courseId: "static-intermediate",
    moduleNumber: 1,
    title: "Tense Mastery",
    description: "Master all the tenses and conditional structures needed for confident intermediate English.",
    icon: "BookOpen",
    order: 0,
  },
  {
    id: "static-int-m2",
    courseId: "static-intermediate",
    moduleNumber: 2,
    title: "Professional and Academic English",
    description: "Develop professional communication skills for emails, meetings, presentations, and academic writing.",
    icon: "BookMarked",
    order: 1,
  },
  {
    id: "static-int-m3",
    courseId: "static-intermediate",
    moduleNumber: 3,
    title: "Advanced Structures",
    description: "Explore cleft sentences, inversion, causative structures, and other advanced patterns.",
    icon: "GraduationCap",
    order: 2,
  },
  {
    id: "static-int-m4",
    courseId: "static-intermediate",
    moduleNumber: 4,
    title: "Professional & Academic",
    description: "Develop professional and academic English skills for writing, presentations, and communication.",
    icon: "Briefcase",
    order: 3,
  },
  {
    id: "static-int-m5",
    courseId: "static-intermediate",
    moduleNumber: 5,
    title: "Fluency & Exam Prep",
    description: "Prepare for B2 level with complex structures, critical thinking, and exam strategies.",
    icon: "Award",
    order: 4,
  },
  // Advanced modules
  {
    id: "static-adv-m1",
    courseId: "static-advanced",
    moduleNumber: 1,
    title: "Sophisticated Grammar",
    description: "Master the subjunctive, cleft sentences, inversion, and other structures that distinguish C1-C2 speakers.",
    icon: "Scale",
    order: 0,
  },
  {
    id: "static-adv-m2",
    courseId: "static-advanced",
    moduleNumber: 2,
    title: "Sophisticated Expression",
    description: "Master diplomacy, humour, rhetoric, and cultural intelligence for sophisticated English communication.",
    icon: "Library",
    order: 1,
  },
  {
    id: "static-adv-m3",
    courseId: "static-advanced",
    moduleNumber: 3,
    title: "Academic and Professional Mastery",
    description: "Develop the language skills needed for academic publishing, conference presentations, and leadership.",
    icon: "GraduationCap",
    order: 2,
  },
  {
    id: "static-adv-m4",
    courseId: "static-advanced",
    moduleNumber: 4,
    title: "Nuanced Communication",
    description: "Master irony, humour, persuasion, and emotional intelligence in English communication.",
    icon: "Brain",
    order: 3,
  },
  {
    id: "static-adv-m5",
    courseId: "static-advanced",
    moduleNumber: 5,
    title: "Native-Like Fluency",
    description: "Achieve near-native fluency with phrasal verbs, regional variations, and language play.",
    icon: "Award",
    order: 4,
  },
];

export const STATIC_LESSONS: StaticLesson[] = [
  // ===== BEGINNER M1: Foundations =====
  {
    id: "static-beg-m1-l1",
    moduleId: "static-beg-m1",
    lessonNumber: 1,
    title: "Present Simple Tense",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/nvVdIJ0las0",
  },
  {
    id: "static-beg-m1-l2",
    moduleId: "static-beg-m1",
    lessonNumber: 2,
    title: "Present Continuous Tense",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/HrG3WXJheyQ",
  },
  {
    id: "static-beg-m1-l3",
    moduleId: "static-beg-m1",
    lessonNumber: 3,
    title: "Articles: A, An, The",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/RDkx4J__-QY",
  },
  {
    id: "static-beg-m1-l4",
    moduleId: "static-beg-m1",
    lessonNumber: 4,
    title: "Prepositions of Place and Time",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/RQ0Qqarel-U",
  },
  {
    id: "static-beg-m1-l5",
    moduleId: "static-beg-m1",
    lessonNumber: 5,
    title: "Past Simple \u2014 Regular Verbs",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/AKXDr2uoYfg",
  },
  {
    id: "static-beg-m1-l6",
    moduleId: "static-beg-m1",
    lessonNumber: 6,
    title: "Past Simple \u2014 Irregular Verbs Part 1",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/24GWC1dDyUM",
  },
  {
    id: "static-beg-m1-l7",
    moduleId: "static-beg-m1",
    lessonNumber: 7,
    title: "Can / Can't \u2014 Ability and Possibility",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/jkNt2LT2s-o",
  },
  {
    id: "static-beg-m1-l8",
    moduleId: "static-beg-m1",
    lessonNumber: 8,
    title: "Question Formation",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/nsBneISa-Y0",
  },
  {
    id: "static-beg-m1-l9",
    moduleId: "static-beg-m1",
    lessonNumber: 9,
    title: "Countable & Uncountable Nouns",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/KJCKugsb9jw",
  },
  {
    id: "static-beg-m1-l10",
    moduleId: "static-beg-m1",
    lessonNumber: 10,
    title: "Basic Conversation \u2014 Introducing Yourself",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/UnEmEbWytI8",
  },

  // ===== BEGINNER M2: Everyday Communication =====
  {
    id: "static-beg-m2-l1",
    moduleId: "static-beg-m2",
    lessonNumber: 1,
    title: "Ordering Food and Drinks",
    contentType: "grammar",
    estimatedMinutes: 12,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/gEdPVA-6rVs",
  },
  {
    id: "static-beg-m2-l2",
    moduleId: "static-beg-m2",
    lessonNumber: 2,
    title: "Asking for and Giving Directions",
    contentType: "grammar",
    estimatedMinutes: 12,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/hKLhepR2KY4",
  },
  {
    id: "static-beg-m2-l3",
    moduleId: "static-beg-m2",
    lessonNumber: 3,
    title: "Making Appointments and Reservations",
    contentType: "grammar",
    estimatedMinutes: 12,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/waN0cJ2S2Xk",
  },
  {
    id: "static-beg-m2-l4",
    moduleId: "static-beg-m2",
    lessonNumber: 4,
    title: "Shopping and Negotiating Prices",
    contentType: "grammar",
    estimatedMinutes: 12,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/TXbYTtHAFlo",
  },
  {
    id: "static-beg-m2-l5",
    moduleId: "static-beg-m2",
    lessonNumber: 5,
    title: "Describing People and Places",
    contentType: "reading",
    estimatedMinutes: 12,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/7bdRcIpN1jU",
  },
  {
    id: "static-beg-m2-l6",
    moduleId: "static-beg-m2",
    lessonNumber: 6,
    title: "Talking About the Weather and Seasons",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/HBhftNOBxS4",
  },
  {
    id: "static-beg-m2-l7",
    moduleId: "static-beg-m2",
    lessonNumber: 7,
    title: "Expressing Likes, Dislikes, and Preferences",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/9SKYec6UlnI",
  },
  {
    id: "static-beg-m2-l8",
    moduleId: "static-beg-m2",
    lessonNumber: 8,
    title: "Making Suggestions and Plans with Friends",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/dH7LF_bbHu0",
  },
  {
    id: "static-beg-m2-l9",
    moduleId: "static-beg-m2",
    lessonNumber: 9,
    title: "Travel and Transportation Essentials",
    contentType: "grammar",
    estimatedMinutes: 12,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/3MUWJ7JbNtw",
  },
  {
    id: "static-beg-m2-l10",
    moduleId: "static-beg-m2",
    lessonNumber: 10,
    title: "Handling Problems and Emergencies",
    contentType: "quiz",
    estimatedMinutes: 12,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/m85MeUJCYac",
  },

  // ===== BEGINNER M3: Expanding Skills =====
  {
    id: "static-beg-m3-l1",
    moduleId: "static-beg-m3",
    lessonNumber: 1,
    title: "Connecting Sentences with And, But, So, Because",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/3qbfcHiUrcI",
  },
  {
    id: "static-beg-m3-l2",
    moduleId: "static-beg-m3",
    lessonNumber: 2,
    title: "Talking About Past Experiences",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/rZS5qlCGCIY",
  },
  {
    id: "static-beg-m3-l3",
    moduleId: "static-beg-m3",
    lessonNumber: 3,
    title: "Making Comparisons: Better, Worse, More, Less",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/wXiD0FdON7k",
  },
  {
    id: "static-beg-m3-l4",
    moduleId: "static-beg-m3",
    lessonNumber: 4,
    title: "Expressing Future Plans: Going to vs. Will",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/n14zCZAvSjI",
  },
  {
    id: "static-beg-m3-l5",
    moduleId: "static-beg-m3",
    lessonNumber: 5,
    title: "Giving Opinions and Agreeing/Disagreeing",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/9SKYec6UlnI",
  },
  {
    id: "static-beg-m3-l6",
    moduleId: "static-beg-m3",
    lessonNumber: 6,
    title: "Talking About Routines and Habits",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/-_M9ztaZH1k",
  },
  {
    id: "static-beg-m3-l7",
    moduleId: "static-beg-m3",
    lessonNumber: 7,
    title: "Describing Health and Feelings",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/7uY2HrQ9qQ8",
  },
  {
    id: "static-beg-m3-l8",
    moduleId: "static-beg-m3",
    lessonNumber: 8,
    title: "Narrating a Simple Story",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/T_qLKu0rFlU",
  },
  {
    id: "static-beg-m3-l9",
    moduleId: "static-beg-m3",
    lessonNumber: 9,
    title: "Talking About Technology and Daily Devices",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/adZ-LYWx95Q",
  },
  {
    id: "static-beg-m3-l10",
    moduleId: "static-beg-m3",
    lessonNumber: 10,
    title: "Cultural Awareness and Social Norms",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/4Gwgls50J30",
  },

  // ===== BEGINNER M4: Practical Communication =====
  {
    id: "static-beg-m4-l1",
    moduleId: "static-beg-m4",
    lessonNumber: 1,
    title: "All Tenses Review — Present, Past, and Future",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/ld7RqdoRAM0",
  },
  {
    id: "static-beg-m4-l2",
    moduleId: "static-beg-m4",
    lessonNumber: 2,
    title: "Articles and Quantifiers Masterclass",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/XxGzMZZ_Hjc",
  },
  {
    id: "static-beg-m4-l3",
    moduleId: "static-beg-m4",
    lessonNumber: 3,
    title: "Prepositions of Time, Place, and Movement",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/p_lgP_XwDig",
  },
  {
    id: "static-beg-m4-l4",
    moduleId: "static-beg-m4",
    lessonNumber: 4,
    title: "Question Formation and Tag Questions",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/YTbGMGcyLPo",
  },
  {
    id: "static-beg-m4-l5",
    moduleId: "static-beg-m4",
    lessonNumber: 5,
    title: "Modal Verbs — Can, Could, Should, Must, Have To",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/36wG9pSYu7Q",
  },
  {
    id: "static-beg-m4-l6",
    moduleId: "static-beg-m4",
    lessonNumber: 6,
    title: "Describing Processes and Instructions",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/RfVQxUF6yTA",
  },
  {
    id: "static-beg-m4-l7",
    moduleId: "static-beg-m4",
    lessonNumber: 7,
    title: "Asking for Clarification and Repetition",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/CYGy_nRzdxU",
  },
  {
    id: "static-beg-m4-l8",
    moduleId: "static-beg-m4",
    lessonNumber: 8,
    title: "Social Media and Modern Communication",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/GPCHtLsh73k",
  },
  {
    id: "static-beg-m4-l9",
    moduleId: "static-beg-m4",
    lessonNumber: 9,
    title: "Talking About Goals and Ambitions",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/fz6jU0hZSL8",
  },
  {
    id: "static-beg-m4-l10",
    moduleId: "static-beg-m4",
    lessonNumber: 10,
    title: "Listening Practice — Conversations and Announcements",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/UnEmEbWytI8",
  },

  // ===== BEGINNER M5: Consolidation =====
  {
    id: "static-beg-m5-l1",
    moduleId: "static-beg-m5",
    lessonNumber: 1,
    title: "Reading Practice — Signs, Menus, and Short Texts",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/U3CJv7mt-dw",
  },
  {
    id: "static-beg-m5-l2",
    moduleId: "static-beg-m5",
    lessonNumber: 2,
    title: "Writing Practice — Emails and Messages",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/moIucWGgvMc",
  },
  {
    id: "static-beg-m5-l3",
    moduleId: "static-beg-m5",
    lessonNumber: 3,
    title: "Speaking Practice — Extended Descriptions",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/tnHANfZHKqQ",
  },
  {
    id: "static-beg-m5-l4",
    moduleId: "static-beg-m5",
    lessonNumber: 4,
    title: "A1-A2 Grammar Checkpoint 1",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/5ESnb5R1SBA",
  },
  {
    id: "static-beg-m5-l5",
    moduleId: "static-beg-m5",
    lessonNumber: 5,
    title: "A1-A2 Grammar Checkpoint 2",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/5ESnb5R1SBA",
  },
  {
    id: "static-beg-m5-l6",
    moduleId: "static-beg-m5",
    lessonNumber: 6,
    title: "Vocabulary Expansion — Everyday Nouns and Verbs",
    contentType: "vocabulary",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/5qiYEKVZAIM",
  },
  {
    id: "static-beg-m5-l7",
    moduleId: "static-beg-m5",
    lessonNumber: 7,
    title: "Vocabulary Expansion — Describing Words and Expressions",
    contentType: "vocabulary",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/zfJAxhbz6PE",
  },
  {
    id: "static-beg-m5-l8",
    moduleId: "static-beg-m5",
    lessonNumber: 8,
    title: "Common A1-A2 Mistakes and How to Fix Them",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/5ESnb5R1SBA",
  },
  {
    id: "static-beg-m5-l9",
    moduleId: "static-beg-m5",
    lessonNumber: 9,
    title: "A2 Practice Test — Listening and Reading",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/X81KzkV2nRc",
  },
  {
    id: "static-beg-m5-l10",
    moduleId: "static-beg-m5",
    lessonNumber: 10,
    title: "A2 Practice Test — Writing and Speaking",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/2KWNUH49BHY",
  },

  // ===== INTERMEDIATE M1: Tense Mastery =====
  {
    id: "static-int-m1-l1",
    moduleId: "static-int-m1",
    lessonNumber: 1,
    title: "Present Perfect Continuous",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/6hNWFy_ujAg",
  },
  {
    id: "static-int-m1-l2",
    moduleId: "static-int-m1",
    lessonNumber: 2,
    title: "Comparatives and Superlatives",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/jz8Fy5qQXu8",
  },
  {
    id: "static-int-m1-l3",
    moduleId: "static-int-m1",
    lessonNumber: 3,
    title: "First, Second, Third Conditionals",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/mJS9Dh5hPNg",
  },
  {
    id: "static-int-m1-l4",
    moduleId: "static-int-m1",
    lessonNumber: 4,
    title: "Mixed Conditionals",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/K_XikoZwM3M",
  },
  {
    id: "static-int-m1-l5",
    moduleId: "static-int-m1",
    lessonNumber: 5,
    title: "Passive Voice: All Tenses",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/CmqOXaSUpFo",
  },
  {
    id: "static-int-m1-l6",
    moduleId: "static-int-m1",
    lessonNumber: 6,
    title: "Reported Speech",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/Mi9UPE2C91I",
  },
  {
    id: "static-int-m1-l7",
    moduleId: "static-int-m1",
    lessonNumber: 7,
    title: "Modal Verbs of Deduction",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/7zbkqNPUQLA",
  },
  {
    id: "static-int-m1-l8",
    moduleId: "static-int-m1",
    lessonNumber: 8,
    title: "Hedging Language",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/MirQVuZsWEo",
  },
  {
    id: "static-int-m1-l9",
    moduleId: "static-int-m1",
    lessonNumber: 9,
    title: "Future Forms: Will, Going to, Present Continuous",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/n14zCZAvSjI",
  },
  {
    id: "static-int-m1-l10",
    moduleId: "static-int-m1",
    lessonNumber: 10,
    title: "Phrasal Verbs in Context",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/t6wqfizHP00",
  },

  // ===== INTERMEDIATE M2: Professional and Academic English =====
  {
    id: "static-int-m2-l1",
    moduleId: "static-int-m2",
    lessonNumber: 1,
    title: "Writing Professional Emails",
    contentType: "grammar",
    estimatedMinutes: 18,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/moIucWGgvMc",
  },
  {
    id: "static-int-m2-l2",
    moduleId: "static-int-m2",
    lessonNumber: 2,
    title: "Participating in Meetings and Discussions",
    contentType: "grammar",
    estimatedMinutes: 18,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/O3kg_dWkmCA",
  },
  {
    id: "static-int-m2-l3",
    moduleId: "static-int-m2",
    lessonNumber: 3,
    title: "Giving Presentations in English",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/fzIxD1jXn44",
  },
  {
    id: "static-int-m2-l4",
    moduleId: "static-int-m2",
    lessonNumber: 4,
    title: "Academic Writing \u2014 Essays and Reports",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/GNL1_tNTqpw",
  },
  {
    id: "static-int-m2-l5",
    moduleId: "static-int-m2",
    lessonNumber: 5,
    title: "Reading Academic and Professional Texts",
    contentType: "reading",
    estimatedMinutes: 18,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/gFXE9n7hrOI",
  },
  {
    id: "static-int-m2-l6",
    moduleId: "static-int-m2",
    lessonNumber: 6,
    title: "Negotiating and Persuading",
    contentType: "grammar",
    estimatedMinutes: 18,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/X5n25N-GDlI",
  },
  {
    id: "static-int-m2-l7",
    moduleId: "static-int-m2",
    lessonNumber: 7,
    title: "Telephone and Video Call English",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/H9jUV2AQphY",
  },
  {
    id: "static-int-m2-l8",
    moduleId: "static-int-m2",
    lessonNumber: 8,
    title: "Networking and Small Talk at Work",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/UcVNwvpQm8A",
  },
  {
    id: "static-int-m2-l9",
    moduleId: "static-int-m2",
    lessonNumber: 9,
    title: "Describing Data, Charts, and Trends",
    contentType: "grammar",
    estimatedMinutes: 18,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/BMU4NnG_zNk",
  },
  {
    id: "static-int-m2-l10",
    moduleId: "static-int-m2",
    lessonNumber: 10,
    title: "Writing CVs, Cover Letters, and Applications",
    contentType: "quiz",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/3etzKSdtvxE",
  },

  // ===== INTERMEDIATE M3: Advanced Structures =====
  {
    id: "static-int-m3-l1",
    moduleId: "static-int-m3",
    lessonNumber: 1,
    title: "Relative Clauses — Defining and Non-Defining",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/eFmfoeTkhH0",
  },
  {
    id: "static-int-m3-l2",
    moduleId: "static-int-m3",
    lessonNumber: 2,
    title: "Gerunds and Infinitives — Choosing Correctly",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/-s1gu725tA4",
  },
  {
    id: "static-int-m3-l3",
    moduleId: "static-int-m3",
    lessonNumber: 3,
    title: "Adjective and Adverb Position and Order",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/wxi3cKICpK8",
  },
  {
    id: "static-int-m3-l4",
    moduleId: "static-int-m3",
    lessonNumber: 4,
    title: "Ellipsis and Substitution for Fluent Speech",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/Q2nEU8YaJso",
  },
  {
    id: "static-int-m3-l5",
    moduleId: "static-int-m3",
    lessonNumber: 5,
    title: "Complex Sentence Connectors — Despite, Although, However",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/ZYd3whIRpik",
  },
  {
    id: "static-int-m3-l6",
    moduleId: "static-int-m3",
    lessonNumber: 6,
    title: "Wishes, Regrets, and Hypothetical Past",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/mYL4IwzUlCY",
  },
  {
    id: "static-int-m3-l7",
    moduleId: "static-int-m3",
    lessonNumber: 7,
    title: "Expressing Probability and Certainty",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/skqj4jOSQU4",
  },
  {
    id: "static-int-m3-l8",
    moduleId: "static-int-m3",
    lessonNumber: 8,
    title: "Emphasis and Focus Structures",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/VvbzG5fXV94",
  },
  {
    id: "static-int-m3-l9",
    moduleId: "static-int-m3",
    lessonNumber: 9,
    title: "Indirect Questions and Polite Requests",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/6muaUJHMnFg",
  },
  {
    id: "static-int-m3-l10",
    moduleId: "static-int-m3",
    lessonNumber: 10,
    title: "Confusing Words and False Friends",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/nR7DbC_fSJU",
  },

  // ===== INTERMEDIATE M4: Professional & Academic =====
  {
    id: "static-int-m4-l1",
    moduleId: "static-int-m4",
    lessonNumber: 1,
    title: "Describing Trends",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/I60ojooYqAA",
  },
  {
    id: "static-int-m4-l2",
    moduleId: "static-int-m4",
    lessonNumber: 2,
    title: "Formal Email Writing",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/moIucWGgvMc",
  },
  {
    id: "static-int-m4-l3",
    moduleId: "static-int-m4",
    lessonNumber: 3,
    title: "Essay Structure and Thesis Statements",
    contentType: "vocabulary",
    estimatedMinutes: 15,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/TotaRoYh60Y",
  },
  {
    id: "static-int-m4-l4",
    moduleId: "static-int-m4",
    lessonNumber: 4,
    title: "Writing Conclusions",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/loeO5uD0cm4",
  },
  {
    id: "static-int-m4-l5",
    moduleId: "static-int-m4",
    lessonNumber: 5,
    title: "Presentation Language",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/fzIxD1jXn44",
  },
  {
    id: "static-int-m4-l6",
    moduleId: "static-int-m4",
    lessonNumber: 6,
    title: "Negotiating and Persuading",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/X5n25N-GDlI",
  },
  {
    id: "static-int-m4-l7",
    moduleId: "static-int-m4",
    lessonNumber: 7,
    title: "Giving and Responding to Feedback",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/CLdbTlgRB1M",
  },
  {
    id: "static-int-m4-l8",
    moduleId: "static-int-m4",
    lessonNumber: 8,
    title: "Academic Vocabulary Expansion",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/1Hqc9Q2ok-k",
  },
  {
    id: "static-int-m4-l9",
    moduleId: "static-int-m4",
    lessonNumber: 9,
    title: "Collocations and Fixed Expressions",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/33uDJ33qt9U",
  },
  {
    id: "static-int-m4-l10",
    moduleId: "static-int-m4",
    lessonNumber: 10,
    title: "Register: Formal vs Informal English",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/9Nx5Y_Hp56U",
  },

  // ===== INTERMEDIATE M5: Fluency & Exam Prep =====
  {
    id: "static-int-m5-l1",
    moduleId: "static-int-m5",
    lessonNumber: 1,
    title: "Vocabulary — Idioms and Phrasal Verbs at B2",
    contentType: "vocabulary",
    estimatedMinutes: 15,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/Emdc5LIhHa4",
  },
  {
    id: "static-int-m5-l2",
    moduleId: "static-int-m5",
    lessonNumber: 2,
    title: "Vocabulary — Academic and Formal Word Lists",
    contentType: "vocabulary",
    estimatedMinutes: 15,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/1Hqc9Q2ok-k",
  },
  {
    id: "static-int-m5-l3",
    moduleId: "static-int-m5",
    lessonNumber: 3,
    title: "Common B1-B2 Mistakes and How to Fix Them",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/5ESnb5R1SBA",
  },
  {
    id: "static-int-m5-l4",
    moduleId: "static-int-m5",
    lessonNumber: 4,
    title: "B1-B2 Grammar Checkpoint 1",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/mQbYZ8_ZRHg",
  },
  {
    id: "static-int-m5-l5",
    moduleId: "static-int-m5",
    lessonNumber: 5,
    title: "B1-B2 Grammar Checkpoint 2",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/mQbYZ8_ZRHg",
  },
  {
    id: "static-int-m5-l6",
    moduleId: "static-int-m5",
    lessonNumber: 6,
    title: "Exam Strategy — IELTS Band 5.5-6.5 Preparation",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/EGBPLDP_qp8",
  },
  {
    id: "static-int-m5-l7",
    moduleId: "static-int-m5",
    lessonNumber: 7,
    title: "Exam Strategy — Cambridge B2 First (FCE) Preparation",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/EdeZp0n0JHw",
  },
  {
    id: "static-int-m5-l8",
    moduleId: "static-int-m5",
    lessonNumber: 8,
    title: "B2 Practice Test — Listening and Reading",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/X81KzkV2nRc",
  },
  {
    id: "static-int-m5-l9",
    moduleId: "static-int-m5",
    lessonNumber: 9,
    title: "B2 Practice Test — Writing and Speaking",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/2KWNUH49BHY",
  },
  {
    id: "static-int-m5-l10",
    moduleId: "static-int-m5",
    lessonNumber: 10,
    title: "From B2 to C1 — Transition Roadmap",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/-2HgLNxqNIY",
  },

  // ===== ADVANCED M1: Sophisticated Grammar =====
  {
    id: "static-adv-m1-l1",
    moduleId: "static-adv-m1",
    lessonNumber: 1,
    title: "The Subjunctive Mood",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/q-FOsRON-7A",
  },
  {
    id: "static-adv-m1-l2",
    moduleId: "static-adv-m1",
    lessonNumber: 2,
    title: "Cleft Sentences for Emphasis",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/Dj0ePce_xmE",
  },
  {
    id: "static-adv-m1-l3",
    moduleId: "static-adv-m1",
    lessonNumber: 3,
    title: "Advanced Hedging and Tentative Language",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/kajoEOfT8w4",
  },
  {
    id: "static-adv-m1-l4",
    moduleId: "static-adv-m1",
    lessonNumber: 4,
    title: "Nominalisation in Academic Writing",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/32e3QlxHq7k",
  },
  {
    id: "static-adv-m1-l5",
    moduleId: "static-adv-m1",
    lessonNumber: 5,
    title: "Discourse Markers and Cohesive Devices",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/cc5PVfbP4is",
  },
  {
    id: "static-adv-m1-l6",
    moduleId: "static-adv-m1",
    lessonNumber: 6,
    title: "Inversion for Rhetorical Effect",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/ivrER84mTOc",
  },
  {
    id: "static-adv-m1-l7",
    moduleId: "static-adv-m1",
    lessonNumber: 7,
    title: "Reporting Verbs and Academic Voice",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/ZE4yH4wxpj4",
  },
  {
    id: "static-adv-m1-l8",
    moduleId: "static-adv-m1",
    lessonNumber: 8,
    title: "Grammatical Cohesion: Ellipsis and Substitution",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/z6Q9Cdwj0OY",
  },
  {
    id: "static-adv-m1-l9",
    moduleId: "static-adv-m1",
    lessonNumber: 9,
    title: "Metaphorical Language and Idiomatic Expression",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/7PEu8vVQl4o",
  },
  {
    id: "static-adv-m1-l10",
    moduleId: "static-adv-m1",
    lessonNumber: 10,
    title: "Critical Evaluation and Argumentation",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/ewBMBu2Apsw",
  },

  // ===== ADVANCED M2: Sophisticated Expression =====
  {
    id: "static-adv-m2-l1",
    moduleId: "static-adv-m2",
    lessonNumber: 1,
    title: "Diplomatic Language and Softening",
    contentType: "grammar",
    estimatedMinutes: 25,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/ruPxnIAjgyg",
  },
  {
    id: "static-adv-m2-l2",
    moduleId: "static-adv-m2",
    lessonNumber: 2,
    title: "Humour, Irony, and Figurative Language",
    contentType: "grammar",
    estimatedMinutes: 25,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/_frEE75cpCk",
  },
  {
    id: "static-adv-m2-l3",
    moduleId: "static-adv-m2",
    lessonNumber: 3,
    title: "Narrative Techniques and Storytelling",
    contentType: "grammar",
    estimatedMinutes: 25,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/hNuAv-42jzY",
  },
  {
    id: "static-adv-m2-l4",
    moduleId: "static-adv-m2",
    lessonNumber: 4,
    title: "Register Shifting \u2014 Formal to Informal",
    contentType: "grammar",
    estimatedMinutes: 25,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/yrUipfy1pLs",
  },
  {
    id: "static-adv-m2-l5",
    moduleId: "static-adv-m2",
    lessonNumber: 5,
    title: "Persuasion and Rhetoric",
    contentType: "reading",
    estimatedMinutes: 25,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/t4ODg51XNYk",
  },
  {
    id: "static-adv-m2-l6",
    moduleId: "static-adv-m2",
    lessonNumber: 6,
    title: "Connotation and Word Choice Precision",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/3j0O68chjnY",
  },
  {
    id: "static-adv-m2-l7",
    moduleId: "static-adv-m2",
    lessonNumber: 7,
    title: "Implying and Inferring \u2014 What's Unsaid",
    contentType: "grammar",
    estimatedMinutes: 25,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/4Eek-X6MoN0",
  },
  {
    id: "static-adv-m2-l8",
    moduleId: "static-adv-m2",
    lessonNumber: 8,
    title: "Advanced Discourse Management",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/cc5PVfbP4is",
  },
  {
    id: "static-adv-m2-l9",
    moduleId: "static-adv-m2",
    lessonNumber: 9,
    title: "Writing Style \u2014 Voice and Tone Development",
    contentType: "grammar",
    estimatedMinutes: 25,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/yTylIzF0OXg",
  },
  {
    id: "static-adv-m2-l10",
    moduleId: "static-adv-m2",
    lessonNumber: 10,
    title: "Cross-Cultural Communication Competence",
    contentType: "quiz",
    estimatedMinutes: 25,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/oTPZWpQ9pbA",
  },

  // ===== ADVANCED M3: Academic and Professional Mastery =====
  {
    id: "static-adv-m3-l1",
    moduleId: "static-adv-m3",
    lessonNumber: 1,
    title: "Writing Research Papers and Literature Reviews",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/08TmrSpSi7Q",
  },
  {
    id: "static-adv-m3-l2",
    moduleId: "static-adv-m3",
    lessonNumber: 2,
    title: "Thesis Statements and Argument Architecture",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/TotaRoYh60Y",
  },
  {
    id: "static-adv-m3-l3",
    moduleId: "static-adv-m3",
    lessonNumber: 3,
    title: "Data Analysis and Research Reporting",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/iRKGHkY-u50",
  },
  {
    id: "static-adv-m3-l4",
    moduleId: "static-adv-m3",
    lessonNumber: 4,
    title: "Executive Communication and Leadership Language",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/Ajpp2dXBn58",
  },
  {
    id: "static-adv-m3-l5",
    moduleId: "static-adv-m3",
    lessonNumber: 5,
    title: "Legal and Contract English",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/MBRrCwOuM00",
  },
  {
    id: "static-adv-m3-l6",
    moduleId: "static-adv-m3",
    lessonNumber: 6,
    title: "Medical and Technical English",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/a1PJRIQrqTo",
  },
  {
    id: "static-adv-m3-l7",
    moduleId: "static-adv-m3",
    lessonNumber: 7,
    title: "Conference Presentations and Public Speaking",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/eVaCpAKdtag",
  },
  {
    id: "static-adv-m3-l8",
    moduleId: "static-adv-m3",
    lessonNumber: 8,
    title: "Media Interviews and Press Communication",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/joABxlByaoU",
  },
  {
    id: "static-adv-m3-l9",
    moduleId: "static-adv-m3",
    lessonNumber: 9,
    title: "Editing and Proofreading at C2 Level",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/lC80UuSkwCQ",
  },
  {
    id: "static-adv-m3-l10",
    moduleId: "static-adv-m3",
    lessonNumber: 10,
    title: "Writing for Publication: Journals and Op-Eds",
    contentType: "quiz",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/gFXE9n7hrOI",
  },

  // ===== ADVANCED M4: Nuanced Communication =====
  {
    id: "static-adv-m4-l1",
    moduleId: "static-adv-m4",
    lessonNumber: 1,
    title: "Irony, Sarcasm, and Subtext",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/SNCAWQL54PM",
  },
  {
    id: "static-adv-m4-l2",
    moduleId: "static-adv-m4",
    lessonNumber: 2,
    title: "Humour in Professional Contexts",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/AKjQHyN_fEQ",
  },
  {
    id: "static-adv-m4-l3",
    moduleId: "static-adv-m4",
    lessonNumber: 3,
    title: "Storytelling and Narrative Techniques",
    contentType: "vocabulary",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/Tn5XiN-GAuE",
  },
  {
    id: "static-adv-m4-l4",
    moduleId: "static-adv-m4",
    lessonNumber: 4,
    title: "Persuasion and Rhetoric",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/X5n25N-GDlI",
  },
  {
    id: "static-adv-m4-l5",
    moduleId: "static-adv-m4",
    lessonNumber: 5,
    title: "Impromptu Speaking",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/lC80UuSkwCQ",
  },
  {
    id: "static-adv-m4-l6",
    moduleId: "static-adv-m4",
    lessonNumber: 6,
    title: "Debating and Counter-Arguments",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/7AqAtewWBQo",
  },
  {
    id: "static-adv-m4-l7",
    moduleId: "static-adv-m4",
    lessonNumber: 7,
    title: "Reframing and Perspective-Shifting",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/PNJR9TG6zw8",
  },
  {
    id: "static-adv-m4-l8",
    moduleId: "static-adv-m4",
    lessonNumber: 8,
    title: "Emotional Intelligence Language",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/JRvhEttaebk",
  },
  {
    id: "static-adv-m4-l9",
    moduleId: "static-adv-m4",
    lessonNumber: 9,
    title: "Diplomatic English for Sensitive Topics",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/iRKGHkY-u50",
  },
  {
    id: "static-adv-m4-l10",
    moduleId: "static-adv-m4",
    lessonNumber: 10,
    title: "Public Speaking and Voice Control",
    contentType: "quiz",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/2JecKsbsswE",
  },

  // ===== ADVANCED M5: Native-Like Fluency =====
  {
    id: "static-adv-m5-l1",
    moduleId: "static-adv-m5",
    lessonNumber: 1,
    title: "Advanced Pronunciation — Intonation and Rhythm",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 0,
    videoUrl: "https://www.youtube.com/embed/hNCQJHrBR84",
  },
  {
    id: "static-adv-m5-l2",
    moduleId: "static-adv-m5",
    lessonNumber: 2,
    title: "Public Speaking Mastery — Keynotes and Panels",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 1,
    videoUrl: "https://www.youtube.com/embed/YvbEODnJVTc",
  },
  {
    id: "static-adv-m5-l3",
    moduleId: "static-adv-m5",
    lessonNumber: 3,
    title: "Writing Policies, White Papers, and Proposals",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: "https://www.youtube.com/embed/SNCAWQL54PM",
  },
  {
    id: "static-adv-m5-l4",
    moduleId: "static-adv-m5",
    lessonNumber: 4,
    title: "Common C1-C2 Mistakes — The Final Polish",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: "https://www.youtube.com/embed/gFXE9n7hrOI",
  },
  {
    id: "static-adv-m5-l5",
    moduleId: "static-adv-m5",
    lessonNumber: 5,
    title: "Vocabulary — Rare and Academic Word Mastery",
    contentType: "vocabulary",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: "https://www.youtube.com/embed/joABxlByaoU",
  },
  {
    id: "static-adv-m5-l6",
    moduleId: "static-adv-m5",
    lessonNumber: 6,
    title: "Vocabulary — Idioms, Proverbs, and Cultural References",
    contentType: "vocabulary",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: "https://www.youtube.com/embed/7Z_FJok8oAw",
  },
  {
    id: "static-adv-m5-l7",
    moduleId: "static-adv-m5",
    lessonNumber: 7,
    title: "Grammar — Edge Cases and Exceptions",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 6,
    videoUrl: "https://www.youtube.com/embed/eVaCpAKdtag",
  },
  {
    id: "static-adv-m5-l8",
    moduleId: "static-adv-m5",
    lessonNumber: 8,
    title: "Writing — Style Guides (APA, MLA, Chicago, Oxford)",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: "https://www.youtube.com/embed/yp6Dn4sa27Y",
  },
  {
    id: "static-adv-m5-l9",
    moduleId: "static-adv-m5",
    lessonNumber: 9,
    title: "Maintaining C2 — Continuous Improvement Strategies",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 8,
    videoUrl: "https://www.youtube.com/embed/yp6Dn4sa27Y",
  },
  {
    id: "static-adv-m5-l10",
    moduleId: "static-adv-m5",
    lessonNumber: 10,
    title: "The Complete C2 Speaker — Final Integration",
    contentType: "quiz",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: "https://www.youtube.com/embed/yp6Dn4sa27Y",
  },
];

export const STATIC_COURSE_BY_SLUG: Record<string, StaticCourse> = Object.fromEntries(STATIC_COURSES.map(c => [c.slug, c]));

export const STATIC_MODULES_BY_COURSE_ID: Record<string, StaticModule[]> = {};
STATIC_MODULES.forEach(m => { (STATIC_MODULES_BY_COURSE_ID[m.courseId] ??= []).push(m); });

export const STATIC_LESSONS_BY_MODULE_ID: Record<string, StaticLesson[]> = {};
STATIC_LESSONS.forEach(l => { (STATIC_LESSONS_BY_MODULE_ID[l.moduleId] ??= []).push(l); });

export const STATIC_LESSON_BY_ID: Record<string, StaticLesson> = Object.fromEntries(STATIC_LESSONS.map(l => [l.id, l]));

// Helper: find course and module for a given lesson ID
export function findCourseForLesson(lessonId: string): { course: StaticCourse; module: StaticModule; lesson: StaticLesson } | null {
  const lesson = STATIC_LESSON_BY_ID[lessonId];
  if (!lesson) return null;
  const courseModule = STATIC_MODULES.find(m => m.id === lesson.moduleId);
  if (!courseModule) return null;
  const course = STATIC_COURSES.find(c => c.id === courseModule.courseId);
  if (!course) return null;
  return { course, module: courseModule, lesson };
}
