// Auto-generated static course data - used as fallback when database is unavailable
// This ensures the app works on Vercel even if the PostgreSQL database is not seeded

export interface StaticCourse {
  id: string; slug: string; title: string; subtitle: string; level: string;
  price: number; compareAtPrice: number | null; description: string; features: string;
  modulesCount: number; lessonsCount: number; estimatedHours: number; imageUrl: string | null; order: number;
}

export interface StaticModule {
  id: string; courseId: string; moduleNumber: number; title: string;
  description: string; icon: string | null; order: number;
}

export interface StaticLesson {
  id: string; moduleId: string; lessonNumber: number; title: string;
  contentType: string; estimatedMinutes: number; order: number;
  videoUrl?: string | null;
}

export const STATIC_COURSES: StaticCourse[] = [
  {
    id: "static-beginner",
    slug: "beginner",
    title: "Beginner English",
    subtitle: "From A1 to A2 \u2014 Build your foundation",
    level: "A1-A2",
    price: 49,
    compareAtPrice: 79,
    description: "Build a solid English foundation from scratch. This comprehensive course takes you from complete beginner to A2 level, covering essential vocabulary, basic grammar, and everyday communication skills. Perfect for those starting their English learning journey.",
    features: "[\"5 comprehensive modules\",\"50 interactive lessons\",\"Grammar fundamentals with exercises\",\"Vocabulary building (500+ words)\",\"Quizzes after every module\",\"Progress tracking dashboard\",\"Completion certificate\"]",
    modulesCount: 5,
    lessonsCount: 50,
    estimatedHours: 30,
    imageUrl: null,
    order: 1,
  },
  {
    id: "static-intermediate",
    slug: "intermediate",
    title: "Intermediate English",
    subtitle: "From B1 to B2 \u2014 Communicate with confidence",
    level: "B1-B2",
    price: 79,
    compareAtPrice: 129,
    description: "Elevate your English to professional and academic levels. Master complex grammar, professional communication, and academic writing. This course bridges the gap between basic English and confident, fluent communication in any context.",
    features: "[\"5 comprehensive modules\",\"50 interactive lessons\",\"Complex grammar mastery\",\"Professional communication skills\",\"Academic English foundations\",\"Quizzes after every module\",\"Progress tracking dashboard\",\"Completion certificate\"]",
    modulesCount: 5,
    lessonsCount: 50,
    estimatedHours: 50,
    imageUrl: null,
    order: 2,
  },
  {
    id: "static-advanced",
    slug: "advanced",
    title: "Advanced English",
    subtitle: "From C1 to C2 \u2014 Master the language",
    level: "C1-C2",
    price: 99,
    compareAtPrice: 169,
    description: "Achieve true English mastery at the highest level. Explore rhetoric, academic publishing, linguistic precision, and cultural intelligence. This course prepares you for C2 proficiency certification and professional excellence in any English-speaking environment.",
    features: "[\"5 comprehensive modules\",\"50 interactive lessons\",\"Academic & professional mastery\",\"Rhetoric & persuasion techniques\",\"Nuanced communication skills\",\"Quizzes after every module\",\"Progress tracking dashboard\",\"Completion certificate\"]",
    modulesCount: 5,
    lessonsCount: 50,
    estimatedHours: 60,
    imageUrl: null,
    order: 3,
  },
];

export const STATIC_MODULES: StaticModule[] = [
  // Beginner modules
  {
    id: "static-beg-m1",
    courseId: "static-beginner",
    moduleNumber: 1,
    title: "Foundations",
    description: "Master the essential building blocks of English: present tenses, articles, prepositions, and basic conversation skills.",
    icon: "HandMetal",
    order: 0,
  },
  {
    id: "static-beg-m2",
    courseId: "static-beginner",
    moduleNumber: 2,
    title: "Building Confidence",
    description: "Build on your foundation with past tenses, future plans, and more complex grammar structures.",
    icon: "Sun",
    order: 1,
  },
  {
    id: "static-beg-m3",
    courseId: "static-beginner",
    moduleNumber: 3,
    title: "Expanding Skills",
    description: "Expand your English skills with perfect tenses, pronouns, and everyday communication.",
    icon: "Users",
    order: 2,
  },
  {
    id: "static-beg-m4",
    courseId: "static-beginner",
    moduleNumber: 4,
    title: "Practical Communication",
    description: "Apply your English skills to real-world situations: phone calls, travel, health, and social media.",
    icon: "MessageCircle",
    order: 3,
  },
  {
    id: "static-beg-m5",
    courseId: "static-beginner",
    moduleNumber: 5,
    title: "Consolidation",
    description: "Review and consolidate everything you have learned, from tenses to pronunciation, and prepare for the A2 level.",
    icon: "Award",
    order: 4,
  },
  // Intermediate modules
  {
    id: "static-int-m1",
    courseId: "static-intermediate",
    moduleNumber: 1,
    title: "Tense Mastery",
    description: "Master all the tenses and conditional structures needed for confident intermediate English.",
    icon: "BookOpen",
    order: 0,
  },
  {
    id: "static-int-m2",
    courseId: "static-intermediate",
    moduleNumber: 2,
    title: "Complex Grammar",
    description: "Master relative clauses, question tags, phrasal verbs, and other intermediate grammar structures.",
    icon: "BookMarked",
    order: 1,
  },
  {
    id: "static-int-m3",
    courseId: "static-intermediate",
    moduleNumber: 3,
    title: "Advanced Structures",
    description: "Explore cleft sentences, inversion, causative structures, and other advanced patterns.",
    icon: "GraduationCap",
    order: 2,
  },
  {
    id: "static-int-m4",
    courseId: "static-intermediate",
    moduleNumber: 4,
    title: "Professional & Academic",
    description: "Develop professional and academic English skills for writing, presentations, and communication.",
    icon: "Briefcase",
    order: 3,
  },
  {
    id: "static-int-m5",
    courseId: "static-intermediate",
    moduleNumber: 5,
    title: "Fluency & Exam Prep",
    description: "Prepare for B2 level with complex structures, critical thinking, and exam strategies.",
    icon: "Award",
    order: 4,
  },
  // Advanced modules
  {
    id: "static-adv-m1",
    courseId: "static-advanced",
    moduleNumber: 1,
    title: "Sophisticated Grammar",
    description: "Master the subjunctive, cleft sentences, inversion, and other structures that distinguish C1-C2 speakers.",
    icon: "Scale",
    order: 0,
  },
  {
    id: "static-adv-m2",
    courseId: "static-advanced",
    moduleNumber: 2,
    title: "Advanced Grammar Mastery",
    description: "Master participle clauses, ellipsis, advanced relative clauses, and other high-level grammar.",
    icon: "Library",
    order: 1,
  },
  {
    id: "static-adv-m3",
    courseId: "static-advanced",
    moduleNumber: 3,
    title: "Academic and Professional Mastery",
    description: "Develop the language skills needed for academic publishing, conference presentations, and leadership.",
    icon: "GraduationCap",
    order: 2,
  },
  {
    id: "static-adv-m4",
    courseId: "static-advanced",
    moduleNumber: 4,
    title: "Nuanced Communication",
    description: "Master irony, humour, persuasion, and emotional intelligence in English communication.",
    icon: "Brain",
    order: 3,
  },
  {
    id: "static-adv-m5",
    courseId: "static-advanced",
    moduleNumber: 5,
    title: "Native-Like Fluency",
    description: "Achieve near-native fluency with phrasal verbs, regional variations, and language play.",
    icon: "Award",
    order: 4,
  },
];

export const STATIC_LESSONS: StaticLesson[] = [
  // ===== BEGINNER M1: Foundations =====
  {
    id: "static-beg-m1-l1",
    moduleId: "static-beg-m1",
    lessonNumber: 1,
    title: "Present Simple \u2014 Daily Routines",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-beg-m1-l2",
    moduleId: "static-beg-m1",
    lessonNumber: 2,
    title: "Present Continuous \u2014 Right Now",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-beg-m1-l3",
    moduleId: "static-beg-m1",
    lessonNumber: 3,
    title: "Articles \u2014 A, An, The",
    contentType: "vocabulary",
    estimatedMinutes: 10,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-beg-m1-l4",
    moduleId: "static-beg-m1",
    lessonNumber: 4,
    title: "Prepositions of Place \u2014 In, On, At",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-beg-m1-l5",
    moduleId: "static-beg-m1",
    lessonNumber: 5,
    title: "Past Simple \u2014 Regular Verbs",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-beg-m1-l6",
    moduleId: "static-beg-m1",
    lessonNumber: 6,
    title: "Past Simple \u2014 Irregular Verbs Part 1",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-beg-m1-l7",
    moduleId: "static-beg-m1",
    lessonNumber: 7,
    title: "Can / Can't \u2014 Ability and Possibility",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-beg-m1-l8",
    moduleId: "static-beg-m1",
    lessonNumber: 8,
    title: "Question Formation",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-beg-m1-l9",
    moduleId: "static-beg-m1",
    lessonNumber: 9,
    title: "Countable & Uncountable Nouns",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-beg-m1-l10",
    moduleId: "static-beg-m1",
    lessonNumber: 10,
    title: "Basic Conversation \u2014 Introducing Yourself",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 9,
    videoUrl: null,
  },

  // ===== BEGINNER M2: Building Confidence =====
  {
    id: "static-beg-m2-l1",
    moduleId: "static-beg-m2",
    lessonNumber: 1,
    title: "Past Simple \u2014 Irregular Verbs Part 2",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-beg-m2-l2",
    moduleId: "static-beg-m2",
    lessonNumber: 2,
    title: "Going to \u2014 Future Plans",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-beg-m2-l3",
    moduleId: "static-beg-m2",
    lessonNumber: 3,
    title: "Would Like \u2014 Polite Requests and Offers",
    contentType: "vocabulary",
    estimatedMinutes: 10,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-beg-m2-l4",
    moduleId: "static-beg-m2",
    lessonNumber: 4,
    title: "Have Got \u2014 Possession",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-beg-m2-l5",
    moduleId: "static-beg-m2",
    lessonNumber: 5,
    title: "Adjectives and Adverbs",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-beg-m2-l6",
    moduleId: "static-beg-m2",
    lessonNumber: 6,
    title: "Comparatives and Superlatives",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-beg-m2-l7",
    moduleId: "static-beg-m2",
    lessonNumber: 7,
    title: "Present Perfect \u2014 Experience (Have you ever...?)",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-beg-m2-l8",
    moduleId: "static-beg-m2",
    lessonNumber: 8,
    title: "Giving Directions",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-beg-m2-l9",
    moduleId: "static-beg-m2",
    lessonNumber: 9,
    title: "Making Appointments",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-beg-m2-l10",
    moduleId: "static-beg-m2",
    lessonNumber: 10,
    title: "Shopping and Restaurants",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 9,
    videoUrl: null,
  },

  // ===== BEGINNER M3: Expanding Skills =====
  {
    id: "static-beg-m3-l1",
    moduleId: "static-beg-m3",
    lessonNumber: 1,
    title: "Present Perfect \u2014 For and Since",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-beg-m3-l2",
    moduleId: "static-beg-m3",
    lessonNumber: 2,
    title: "Too and Enough",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-beg-m3-l3",
    moduleId: "static-beg-m3",
    lessonNumber: 3,
    title: "Somebody, Anybody, Nobody, Everybody",
    contentType: "vocabulary",
    estimatedMinutes: 10,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-beg-m3-l4",
    moduleId: "static-beg-m3",
    lessonNumber: 4,
    title: "Reflexive Pronouns",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-beg-m3-l5",
    moduleId: "static-beg-m3",
    lessonNumber: 5,
    title: "Gerunds (-ing as noun)",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-beg-m3-l6",
    moduleId: "static-beg-m3",
    lessonNumber: 6,
    title: "Used to \u2014 Past Habits",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-beg-m3-l7",
    moduleId: "static-beg-m3",
    lessonNumber: 7,
    title: "Will \u2014 Spontaneous Decisions",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-beg-m3-l8",
    moduleId: "static-beg-m3",
    lessonNumber: 8,
    title: "Describing People and Places",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-beg-m3-l9",
    moduleId: "static-beg-m3",
    lessonNumber: 9,
    title: "Making Suggestions",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-beg-m3-l10",
    moduleId: "static-beg-m3",
    lessonNumber: 10,
    title: "Talking About Weather and Seasons",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 9,
    videoUrl: null,
  },

  // ===== BEGINNER M4: Practical Communication =====
  {
    id: "static-beg-m4-l1",
    moduleId: "static-beg-m4",
    lessonNumber: 1,
    title: "Telephone English",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-beg-m4-l2",
    moduleId: "static-beg-m4",
    lessonNumber: 2,
    title: "Booking Hotels and Flights",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-beg-m4-l3",
    moduleId: "static-beg-m4",
    lessonNumber: 3,
    title: "At the Doctor",
    contentType: "vocabulary",
    estimatedMinutes: 10,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-beg-m4-l4",
    moduleId: "static-beg-m4",
    lessonNumber: 4,
    title: "Talking About Movies and Books",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-beg-m4-l5",
    moduleId: "static-beg-m4",
    lessonNumber: 5,
    title: "Giving Opinions",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-beg-m4-l6",
    moduleId: "static-beg-m4",
    lessonNumber: 6,
    title: "Talking About Future Plans",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-beg-m4-l7",
    moduleId: "static-beg-m4",
    lessonNumber: 7,
    title: "Describing a Process",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-beg-m4-l8",
    moduleId: "static-beg-m4",
    lessonNumber: 8,
    title: "Talking About Health and Fitness",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-beg-m4-l9",
    moduleId: "static-beg-m4",
    lessonNumber: 9,
    title: "Social Media Vocabulary",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-beg-m4-l10",
    moduleId: "static-beg-m4",
    lessonNumber: 10,
    title: "Travel and Tourism",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 9,
    videoUrl: null,
  },

  // ===== BEGINNER M5: Consolidation =====
  {
    id: "static-beg-m5-l1",
    moduleId: "static-beg-m5",
    lessonNumber: 1,
    title: "Review: Present Tenses",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-beg-m5-l2",
    moduleId: "static-beg-m5",
    lessonNumber: 2,
    title: "Review: Past Tenses",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-beg-m5-l3",
    moduleId: "static-beg-m5",
    lessonNumber: 3,
    title: "Review: Future Forms",
    contentType: "vocabulary",
    estimatedMinutes: 10,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-beg-m5-l4",
    moduleId: "static-beg-m5",
    lessonNumber: 4,
    title: "Review: Modal Verbs",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-beg-m5-l5",
    moduleId: "static-beg-m5",
    lessonNumber: 5,
    title: "Review: Prepositions",
    contentType: "reading",
    estimatedMinutes: 10,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-beg-m5-l6",
    moduleId: "static-beg-m5",
    lessonNumber: 6,
    title: "Review: Articles",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-beg-m5-l7",
    moduleId: "static-beg-m5",
    lessonNumber: 7,
    title: "Common Mistakes at A2 Level",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-beg-m5-l8",
    moduleId: "static-beg-m5",
    lessonNumber: 8,
    title: "Pronunciation Focus: Word Stress",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-beg-m5-l9",
    moduleId: "static-beg-m5",
    lessonNumber: 9,
    title: "Connected Speech and Weak Forms",
    contentType: "grammar",
    estimatedMinutes: 10,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-beg-m5-l10",
    moduleId: "static-beg-m5",
    lessonNumber: 10,
    title: "Final Review: A1\u2192A2 Progress Check",
    contentType: "quiz",
    estimatedMinutes: 10,
    order: 9,
    videoUrl: null,
  },

  // ===== INTERMEDIATE M1: Tense Mastery =====
  {
    id: "static-int-m1-l1",
    moduleId: "static-int-m1",
    lessonNumber: 1,
    title: "Present Perfect Continuous",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-int-m1-l2",
    moduleId: "static-int-m1",
    lessonNumber: 2,
    title: "Comparative & Superlative Adjectives",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-int-m1-l3",
    moduleId: "static-int-m1",
    lessonNumber: 3,
    title: "First Conditional (Real Future)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-int-m1-l4",
    moduleId: "static-int-m1",
    lessonNumber: 4,
    title: "Second Conditional (Unreal Present/Future)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-int-m1-l5",
    moduleId: "static-int-m1",
    lessonNumber: 5,
    title: "Third Conditional (Unreal Past)",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-int-m1-l6",
    moduleId: "static-int-m1",
    lessonNumber: 6,
    title: "Mixed Conditionals (Past \u2192 Present)",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-int-m1-l7",
    moduleId: "static-int-m1",
    lessonNumber: 7,
    title: "Passive Voice (All Tenses)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-int-m1-l8",
    moduleId: "static-int-m1",
    lessonNumber: 8,
    title: "Reported Speech",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-int-m1-l9",
    moduleId: "static-int-m1",
    lessonNumber: 9,
    title: "Modal Verbs of Deduction",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-int-m1-l10",
    moduleId: "static-int-m1",
    lessonNumber: 10,
    title: "Hedging Language & Softening",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 9,
    videoUrl: null,
  },

  // ===== INTERMEDIATE M2: Complex Grammar =====
  {
    id: "static-int-m2-l1",
    moduleId: "static-int-m2",
    lessonNumber: 1,
    title: "Relative Clauses (who, which, that, whose)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-int-m2-l2",
    moduleId: "static-int-m2",
    lessonNumber: 2,
    title: "Question Tags (isn't it?, haven't you?)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-int-m2-l3",
    moduleId: "static-int-m2",
    lessonNumber: 3,
    title: "Gerunds vs Infinitives",
    contentType: "vocabulary",
    estimatedMinutes: 15,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-int-m2-l4",
    moduleId: "static-int-m2",
    lessonNumber: 4,
    title: "Phrasal Verbs (separable vs inseparable)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-int-m2-l5",
    moduleId: "static-int-m2",
    lessonNumber: 5,
    title: "Articles Review (a/an, the, zero article)",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-int-m2-l6",
    moduleId: "static-int-m2",
    lessonNumber: 6,
    title: "Past Perfect Simple",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-int-m2-l7",
    moduleId: "static-int-m2",
    lessonNumber: 7,
    title: "Past Perfect Continuous",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-int-m2-l8",
    moduleId: "static-int-m2",
    lessonNumber: 8,
    title: "Future Forms (will, going to, present continuous)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-int-m2-l9",
    moduleId: "static-int-m2",
    lessonNumber: 9,
    title: "Expressing Wishes (I wish, If only)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-int-m2-l10",
    moduleId: "static-int-m2",
    lessonNumber: 10,
    title: "Linking Words and Discourse Markers",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 9,
    videoUrl: null,
  },

  // ===== INTERMEDIATE M3: Advanced Structures =====
  {
    id: "static-int-m3-l1",
    moduleId: "static-int-m3",
    lessonNumber: 1,
    title: "Cleft Sentences (What I need is...)",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-int-m3-l2",
    moduleId: "static-int-m3",
    lessonNumber: 2,
    title: "Inversion for Emphasis (Never have I...)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-int-m3-l3",
    moduleId: "static-int-m3",
    lessonNumber: 3,
    title: "So / Such / Too / Enough",
    contentType: "vocabulary",
    estimatedMinutes: 15,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-int-m3-l4",
    moduleId: "static-int-m3",
    lessonNumber: 4,
    title: "Used to / Be used to / Get used to",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-int-m3-l5",
    moduleId: "static-int-m3",
    lessonNumber: 5,
    title: "Have Something Done (causative)",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-int-m3-l6",
    moduleId: "static-int-m3",
    lessonNumber: 6,
    title: "Indirect Questions",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-int-m3-l7",
    moduleId: "static-int-m3",
    lessonNumber: 7,
    title: "Quantifiers (few, little, many, much, some, any)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-int-m3-l8",
    moduleId: "static-int-m3",
    lessonNumber: 8,
    title: "Word Order in Questions",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-int-m3-l9",
    moduleId: "static-int-m3",
    lessonNumber: 9,
    title: "Prepositions of Time and Place (advanced)",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-int-m3-l10",
    moduleId: "static-int-m3",
    lessonNumber: 10,
    title: "Confusing Words (affect/effect, advice/advise)",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 9,
    videoUrl: null,
  },

  // ===== INTERMEDIATE M4: Professional & Academic =====
  {
    id: "static-int-m4-l1",
    moduleId: "static-int-m4",
    lessonNumber: 1,
    title: "Describing Trends",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-int-m4-l2",
    moduleId: "static-int-m4",
    lessonNumber: 2,
    title: "Formal Email Writing",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-int-m4-l3",
    moduleId: "static-int-m4",
    lessonNumber: 3,
    title: "Essay Structure and Thesis Statements",
    contentType: "vocabulary",
    estimatedMinutes: 15,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-int-m4-l4",
    moduleId: "static-int-m4",
    lessonNumber: 4,
    title: "Writing Conclusions",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-int-m4-l5",
    moduleId: "static-int-m4",
    lessonNumber: 5,
    title: "Presentation Language",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-int-m4-l6",
    moduleId: "static-int-m4",
    lessonNumber: 6,
    title: "Negotiating and Persuading",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-int-m4-l7",
    moduleId: "static-int-m4",
    lessonNumber: 7,
    title: "Giving and Responding to Feedback",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-int-m4-l8",
    moduleId: "static-int-m4",
    lessonNumber: 8,
    title: "Academic Vocabulary Expansion",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-int-m4-l9",
    moduleId: "static-int-m4",
    lessonNumber: 9,
    title: "Collocations and Fixed Expressions",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-int-m4-l10",
    moduleId: "static-int-m4",
    lessonNumber: 10,
    title: "Register: Formal vs Informal English",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 9,
    videoUrl: null,
  },

  // ===== INTERMEDIATE M5: Fluency & Exam Prep =====
  {
    id: "static-int-m5-l1",
    moduleId: "static-int-m5",
    lessonNumber: 1,
    title: "Complex Sentence Structures",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-int-m5-l2",
    moduleId: "static-int-m5",
    lessonNumber: 2,
    title: "Subjunctive Mood",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-int-m5-l3",
    moduleId: "static-int-m5",
    lessonNumber: 3,
    title: "Advanced Conditional Patterns",
    contentType: "vocabulary",
    estimatedMinutes: 15,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-int-m5-l4",
    moduleId: "static-int-m5",
    lessonNumber: 4,
    title: "Nominalisation",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-int-m5-l5",
    moduleId: "static-int-m5",
    lessonNumber: 5,
    title: "Cohesion and Coherence in Writing",
    contentType: "reading",
    estimatedMinutes: 15,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-int-m5-l6",
    moduleId: "static-int-m5",
    lessonNumber: 6,
    title: "Critical Thinking Language",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-int-m5-l7",
    moduleId: "static-int-m5",
    lessonNumber: 7,
    title: "Paraphrasing and Summarising",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-int-m5-l8",
    moduleId: "static-int-m5",
    lessonNumber: 8,
    title: "Exam Strategy: Time Management",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-int-m5-l9",
    moduleId: "static-int-m5",
    lessonNumber: 9,
    title: "Common B2 Exam Mistakes to Avoid",
    contentType: "grammar",
    estimatedMinutes: 15,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-int-m5-l10",
    moduleId: "static-int-m5",
    lessonNumber: 10,
    title: "Final Review: B1\u2192B2 Progress Check",
    contentType: "quiz",
    estimatedMinutes: 15,
    order: 9,
    videoUrl: null,
  },

  // ===== ADVANCED M1: Sophisticated Grammar =====
  {
    id: "static-adv-m1-l1",
    moduleId: "static-adv-m1",
    lessonNumber: 1,
    title: "Subjunctive Mood",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-adv-m1-l2",
    moduleId: "static-adv-m1",
    lessonNumber: 2,
    title: "Cleft Sentences and Emphasis",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-adv-m1-l3",
    moduleId: "static-adv-m1",
    lessonNumber: 3,
    title: "Hedging and Tentative Language",
    contentType: "vocabulary",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-adv-m1-l4",
    moduleId: "static-adv-m1",
    lessonNumber: 4,
    title: "Nominalisation",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-adv-m1-l5",
    moduleId: "static-adv-m1",
    lessonNumber: 5,
    title: "Discourse Markers for Sophisticated Writing",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-adv-m1-l6",
    moduleId: "static-adv-m1",
    lessonNumber: 6,
    title: "Inversion for Emphasis",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-adv-m1-l7",
    moduleId: "static-adv-m1",
    lessonNumber: 7,
    title: "Advanced Reporting Verbs",
    contentType: "vocabulary",
    estimatedMinutes: 20,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-adv-m1-l8",
    moduleId: "static-adv-m1",
    lessonNumber: 8,
    title: "Academic Writing \u2014 Cohesion and Coherence",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-adv-m1-l9",
    moduleId: "static-adv-m1",
    lessonNumber: 9,
    title: "Metaphorical and Idiomatic Language",
    contentType: "vocabulary",
    estimatedMinutes: 20,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-adv-m1-l10",
    moduleId: "static-adv-m1",
    lessonNumber: 10,
    title: "Critical Thinking and Evaluation Language",
    contentType: "quiz",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: null,
  },

  // ===== ADVANCED M2: Advanced Grammar Mastery =====
  {
    id: "static-adv-m2-l1",
    moduleId: "static-adv-m2",
    lessonNumber: 1,
    title: "Complex Conditionals and Alternatives",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-adv-m2-l2",
    moduleId: "static-adv-m2",
    lessonNumber: 2,
    title: "Participle Clauses (Having finished, Walking down...)",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-adv-m2-l3",
    moduleId: "static-adv-m2",
    lessonNumber: 3,
    title: "Ellipsis and Substitution in Formal Contexts",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-adv-m2-l4",
    moduleId: "static-adv-m2",
    lessonNumber: 4,
    title: "Advanced Relative Clauses",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-adv-m2-l5",
    moduleId: "static-adv-m2",
    lessonNumber: 5,
    title: "Future in the Past",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-adv-m2-l6",
    moduleId: "static-adv-m2",
    lessonNumber: 6,
    title: "Emphatic Structures (do/did, What I did was...)",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-adv-m2-l7",
    moduleId: "static-adv-m2",
    lessonNumber: 7,
    title: "Complementation Patterns (verb + wh-clause)",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-adv-m2-l8",
    moduleId: "static-adv-m2",
    lessonNumber: 8,
    title: "Verbs of Perception + Object + Bare Infinitive",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-adv-m2-l9",
    moduleId: "static-adv-m2",
    lessonNumber: 9,
    title: "Transitivity and Verb Patterns",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-adv-m2-l10",
    moduleId: "static-adv-m2",
    lessonNumber: 10,
    title: "Coordination and Subordination Mastery",
    contentType: "quiz",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: null,
  },

  // ===== ADVANCED M3: Academic and Professional Mastery =====
  {
    id: "static-adv-m3-l1",
    moduleId: "static-adv-m3",
    lessonNumber: 1,
    title: "Writing Abstracts and Executive Summaries",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-adv-m3-l2",
    moduleId: "static-adv-m3",
    lessonNumber: 2,
    title: "Literature Review Language",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-adv-m3-l3",
    moduleId: "static-adv-m3",
    lessonNumber: 3,
    title: "Methodology Descriptions",
    contentType: "vocabulary",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-adv-m3-l4",
    moduleId: "static-adv-m3",
    lessonNumber: 4,
    title: "Results and Discussion Sections",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-adv-m3-l5",
    moduleId: "static-adv-m3",
    lessonNumber: 5,
    title: "Research Proposals",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-adv-m3-l6",
    moduleId: "static-adv-m3",
    lessonNumber: 6,
    title: "Conference Presentations",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-adv-m3-l7",
    moduleId: "static-adv-m3",
    lessonNumber: 7,
    title: "Negotiating and Mediating Conflicts",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-adv-m3-l8",
    moduleId: "static-adv-m3",
    lessonNumber: 8,
    title: "Cross-Cultural Communication",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-adv-m3-l9",
    moduleId: "static-adv-m3",
    lessonNumber: 9,
    title: "Crisis Communication",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-adv-m3-l10",
    moduleId: "static-adv-m3",
    lessonNumber: 10,
    title: "Leadership Language",
    contentType: "quiz",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: null,
  },

  // ===== ADVANCED M4: Nuanced Communication =====
  {
    id: "static-adv-m4-l1",
    moduleId: "static-adv-m4",
    lessonNumber: 1,
    title: "Irony, Sarcasm, and Subtext",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-adv-m4-l2",
    moduleId: "static-adv-m4",
    lessonNumber: 2,
    title: "Humour in Professional Contexts",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-adv-m4-l3",
    moduleId: "static-adv-m4",
    lessonNumber: 3,
    title: "Storytelling and Narrative Techniques",
    contentType: "vocabulary",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-adv-m4-l4",
    moduleId: "static-adv-m4",
    lessonNumber: 4,
    title: "Persuasion and Rhetoric",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-adv-m4-l5",
    moduleId: "static-adv-m4",
    lessonNumber: 5,
    title: "Impromptu Speaking",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-adv-m4-l6",
    moduleId: "static-adv-m4",
    lessonNumber: 6,
    title: "Debating and Counter-Arguments",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-adv-m4-l7",
    moduleId: "static-adv-m4",
    lessonNumber: 7,
    title: "Reframing and Perspective-Shifting",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-adv-m4-l8",
    moduleId: "static-adv-m4",
    lessonNumber: 8,
    title: "Emotional Intelligence Language",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-adv-m4-l9",
    moduleId: "static-adv-m4",
    lessonNumber: 9,
    title: "Diplomatic English for Sensitive Topics",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-adv-m4-l10",
    moduleId: "static-adv-m4",
    lessonNumber: 10,
    title: "Public Speaking and Voice Control",
    contentType: "quiz",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: null,
  },

  // ===== ADVANCED M5: Native-Like Fluency =====
  {
    id: "static-adv-m5-l1",
    moduleId: "static-adv-m5",
    lessonNumber: 1,
    title: "Phrasal Verbs at C2 Level",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 0,
    videoUrl: null,
  },
  {
    id: "static-adv-m5-l2",
    moduleId: "static-adv-m5",
    lessonNumber: 2,
    title: "Regional Variations (UK vs US vs AUS)",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 1,
    videoUrl: null,
  },
  {
    id: "static-adv-m5-l3",
    moduleId: "static-adv-m5",
    lessonNumber: 3,
    title: "Archaic and Literary Expressions",
    contentType: "vocabulary",
    estimatedMinutes: 20,
    order: 2,
    videoUrl: null,
  },
  {
    id: "static-adv-m5-l4",
    moduleId: "static-adv-m5",
    lessonNumber: 4,
    title: "Professional Register Variations",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 3,
    videoUrl: null,
  },
  {
    id: "static-adv-m5-l5",
    moduleId: "static-adv-m5",
    lessonNumber: 5,
    title: "Imprecision and Vagueness (deliberate)",
    contentType: "reading",
    estimatedMinutes: 20,
    order: 4,
    videoUrl: null,
  },
  {
    id: "static-adv-m5-l6",
    moduleId: "static-adv-m5",
    lessonNumber: 6,
    title: "Repair Strategies in Speech",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 5,
    videoUrl: null,
  },
  {
    id: "static-adv-m5-l7",
    moduleId: "static-adv-m5",
    lessonNumber: 7,
    title: "Coherence in Extended Discourse",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 6,
    videoUrl: null,
  },
  {
    id: "static-adv-m5-l8",
    moduleId: "static-adv-m5",
    lessonNumber: 8,
    title: "Intertextuality and Allusion",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 7,
    videoUrl: null,
  },
  {
    id: "static-adv-m5-l9",
    moduleId: "static-adv-m5",
    lessonNumber: 9,
    title: "Language Play and Wordplay",
    contentType: "grammar",
    estimatedMinutes: 20,
    order: 8,
    videoUrl: null,
  },
  {
    id: "static-adv-m5-l10",
    moduleId: "static-adv-m5",
    lessonNumber: 10,
    title: "Final Review: C1\u2192C2 Progress Check",
    contentType: "quiz",
    estimatedMinutes: 20,
    order: 9,
    videoUrl: null,
  },
];

export const STATIC_COURSE_BY_SLUG: Record<string, StaticCourse> = Object.fromEntries(STATIC_COURSES.map(c => [c.slug, c]));

export const STATIC_MODULES_BY_COURSE_ID: Record<string, StaticModule[]> = {};
STATIC_MODULES.forEach(m => { (STATIC_MODULES_BY_COURSE_ID[m.courseId] ??= []).push(m); });

export const STATIC_LESSONS_BY_MODULE_ID: Record<string, StaticLesson[]> = {};
STATIC_LESSONS.forEach(l => { (STATIC_LESSONS_BY_MODULE_ID[l.moduleId] ??= []).push(l); });

export const STATIC_LESSON_BY_ID: Record<string, StaticLesson> = Object.fromEntries(STATIC_LESSONS.map(l => [l.id, l]));

// Helper: find course and module for a given lesson ID
export function findCourseForLesson(lessonId: string): { course: StaticCourse; module: StaticModule; lesson: StaticLesson } | null {
  const lesson = STATIC_LESSON_BY_ID[lessonId];
  if (!lesson) return null;
  const courseModule = STATIC_MODULES.find(m => m.id === lesson.moduleId);
  if (!courseModule) return null;
  const course = STATIC_COURSES.find(c => c.id === courseModule.courseId);
  if (!course) return null;
  return { course, module: courseModule, lesson };
}
