'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuthStore } from '@/lib/auth-store';
import { Navbar } from '@/components/navbar';
import { trackTestStart, trackTestComplete, trackTestAbandon } from '@/lib/analytics';
import {
  Headphones, Mic, BookOpen, PenTool, Play, Square, Volume2,
  ChevronRight, ChevronLeft, Clock, AlertCircle, CheckCircle2,
  Loader2, ArrowRight, Award, Sparkles, RotateCcw, VolumeX,
  MicOff, Send, X, LogIn, SpellCheck, BookMarked
} from 'lucide-react';

/* ======================================================
   TYPES
   ====================================================== */
interface SpeakingEvaluation {
  cefrLevel: string;
  score: number;
  feedback: string;
  strengths: string[];
  improvements: string[];
  dimensions: {
    grammar: { score: number; feedback: string };
    vocabulary: { score: number; feedback: string };
    fluency: { score: number; feedback: string };
    pronunciation: { score: number; feedback: string };
    coherence: { score: number; feedback: string };
    interaction: { score: number; feedback: string };
  };
}

interface WritingEvaluation {
  cefrLevel: string;
  score: number;
  feedback: string;
  strengths: string[];
  improvements: string[];
}

type TestPhase = 'select' | 'grammar' | 'vocabulary' | 'reading' | 'listening' | 'speaking' | 'writing' | 'results';
type SkillStatus = 'pending' | 'in_progress' | 'completed';

interface ApiQuestionSet {
  grammar: Array<{ id: string; text: string; options: string[]; level: string; category: string; difficultyTier: number }>;
  vocabulary: Array<{ id: string; text: string; options: string[]; level: string; category: string; difficultyTier: number }>;
  reading: Array<{ id: string; level: string; title: string | null; passageText: string; questions: Array<{ id: string; questionText: string; options: string[]; sortOrder: number }> }>;
  listening: Array<{ id: string; level: string; scriptText: string; audioUrl: string | null; context: string | null; questions: Array<{ id: string; questionText: string; options: string[]; sortOrder: number }> }>;
  speaking: { id: string; level: string; promptText: string; preparationTime: number; responseTime: number } | null;
  writing: { id: string; level: string; promptText: string; minWords: number; maxWords: number } | null;
}

/* ======================================================
   HELPER: NATURAL TTS via server-side API
   Providers: Gemini TTS (Kore) → Cloud TTS (Neural2-F) → z-ai TTS (kazi)
   No browser speechSynthesis fallback — server must provide audio
   ====================================================== */
// Cache audio blobs by listening item ID so we don't re-fetch
const audioBlobCache = new Map<string, string>();

async function generateNaturalSpeech(itemId: string, text: string): Promise<string> {
  // Check cache first
  const cached = audioBlobCache.get(itemId);
  if (cached) return cached;

  const res = await fetch('/api/tts/', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text }),
  });

  if (!res.ok) {
    const errData = await res.json().catch(() => ({}));
    const provider = res.headers.get('X-TTS-Provider') || 'unknown';
    console.error(`[TTS] Generation failed (status ${res.status}, provider: ${provider}):`, errData);
    throw new Error(`TTS generation failed: ${errData.error || res.statusText}`);
  }

  // Log which provider was used
  const provider = res.headers.get('X-TTS-Provider') || 'unknown';
  console.log(`[TTS] Audio generated by: ${provider}`);

  const blob = await res.blob();
  const url = URL.createObjectURL(blob);
  audioBlobCache.set(itemId, url);
  return url;
}

/* ======================================================
   MAIN TEST PAGE
   ====================================================== */
export default function TestPage() {
  const router = useRouter();
  const { isAuthenticated, isLoading: authIsLoading, user } = useAuthStore();

  // API-driven question state
  const [apiQuestions, setApiQuestions] = useState<ApiQuestionSet | null>(null);
  const [assessmentId, setAssessmentId] = useState<string | null>(null);
  const [isLoadingQuestions, setIsLoadingQuestions] = useState(true);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [resumingAssessment, setResumingAssessment] = useState(false);

  // Test state
  const [phase, setPhase] = useState<TestPhase>('select');

  // Fetch questions on mount
  useEffect(() => {
    if (!isAuthenticated) return;
    const initAssessment = async () => {
      setIsLoadingQuestions(true);
      try {
        // First, check for in-progress assessment (GET, does NOT consume a credit)
        const getRes = await fetch('/api/assessments/start/', { method: 'GET' });
        if (getRes.ok) {
          const getData = await getRes.json();
          if (getData.hasInProgress && getData.assessment) {
            // Resume: fetch questions for the in-progress assessment
            setAssessmentId(getData.assessment.id);
            setResumingAssessment(true);
            try {
              const qRes = await fetch(`/api/assessments/${getData.assessment.id}/questions`);
              if (qRes.ok) {
                const qData = await qRes.json();
                if (qData.questions) {
                  setApiQuestions(qData.questions);
                  setResumingAssessment(false);
                  return; // Successfully resumed — skip POST
                }
              } else {
                // Questions endpoint returned an error — show a clear message, don't fall through to POST
                const qErrData = await qRes.json().catch(() => ({}));
                setError(`Could not load your in-progress assessment: ${qErrData.error || 'Unknown error'}. Try refreshing the page.`);
                setResumingAssessment(false);
                return;
              }
            } catch {
              // Network error fetching questions — don't fall through to POST (it would create a new assessment)
              setError('Network error while loading your in-progress assessment. Please check your connection and refresh the page.');
              setResumingAssessment(false);
              return;
            }
          }
        }

        // No in-progress assessment found — start a new one (POST consumes a credit)
        const postRes = await fetch('/api/assessments/start/', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
        });
        const postData = await postRes.json();

        if (postRes.ok) {
          if (postData.questions) {
            setAssessmentId(postData.assessment.id);
            setApiQuestions(postData.questions);
            setResumingAssessment(false);
          } else {
            // POST returned an existing in-progress assessment without questions
            // This can happen if the GET above failed or returned hasInProgress=false incorrectly
            setAssessmentId(postData.assessment.id);
            setResumingAssessment(true);
            try {
              const qRes = await fetch(`/api/assessments/${postData.assessment.id}/questions`);
              if (qRes.ok) {
                const qData = await qRes.json();
                if (qData.questions) {
                  setApiQuestions(qData.questions);
                  setResumingAssessment(false);
                } else {
                  setError('Your assessment questions could not be loaded. Please refresh the page to try again.');
                }
              } else {
                setError('Failed to fetch assessment questions. Please refresh the page.');
              }
            } catch {
              setError('Network error. Please check your connection and refresh the page.');
            }
          }
        } else {
          if (postData.code === 'NO_CREDITS') {
            setError('You have no test credits remaining. Please upgrade your plan to continue.');
          } else if (postData.code === 'EMAIL_NOT_VERIFIED') {
            setError('Please verify your email address before taking a test. Check your inbox for the verification link.');
          } else {
            setError(postData.message || 'Failed to start assessment.');
          }
        }
      } catch {
        setError('Failed to load test questions. Please check your connection and refresh the page.');
      } finally {
        setIsLoadingQuestions(false);
      }
    };
    initAssessment();
  }, [isAuthenticated]);

  // Skill tracking
  const [skillStatuses, setSkillStatuses] = useState<Record<string, SkillStatus>>({
    grammar: 'pending',
    vocabulary: 'pending',
    reading: 'pending',
    listening: 'pending',
    speaking: 'pending',
    writing: 'pending',
  });

  // Grammar state
  const [grammarIdx, setGrammarIdx] = useState(0);
  const [grammarAnswers, setGrammarAnswers] = useState<Record<string, number>>({});

  // Vocabulary state
  const [vocabIdx, setVocabIdx] = useState(0);
  const [vocabAnswers, setVocabAnswers] = useState<Record<string, number>>({});

  // Reading state
  const [readingIdx, setReadingIdx] = useState(0);
  const [readingAnswers, setReadingAnswers] = useState<Record<string, number>>({});

  // Listening state
  const [listeningIdx, setListeningIdx] = useState(0);
  const [listeningAnswers, setListeningAnswers] = useState<Record<string, number>>({});
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [audioLoading, setAudioLoading] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  // Pre-fetch listening audio in the background when questions load
  useEffect(() => {
    const items = apiQuestions?.listening;
    if (!items || items.length === 0) return;
    // Pre-generate audio for all listening items in background
    const prefetch = async () => {
      for (const item of items) {
        if (!audioBlobCache.has(item.id)) {
          try {
            await generateNaturalSpeech(item.id, item.scriptText);
          } catch {
            // Silently fail - will retry on play
          }
        }
      }
    };
    prefetch();
  }, [apiQuestions?.listening]);

  // Speaking state
  const [isRecording, setIsRecording] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [isPrepTime, setIsPrepTime] = useState(false);
  const [prepTimeLeft, setPrepTimeLeft] = useState(0);
  const [speakingTranscript, setSpeakingTranscript] = useState('');
  const [speechNotSupported, setSpeechNotSupported] = useState(false);
  const [speakingEvaluations, setSpeakingEvaluations] = useState<Record<string, SpeakingEvaluation>>({});
  const [evaluatingSpeaking, setEvaluatingSpeaking] = useState(false);
  const recognitionRef = useRef<any>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Writing state
  const [writingTexts, setWritingTexts] = useState<Record<string, string>>({});
  const [writingEvaluations, setWritingEvaluations] = useState<Record<string, WritingEvaluation>>({});
  const [evaluatingWriting, setEvaluatingWriting] = useState(false);

  // Browser speech recognition support (for speaking test warning)
  const [speechSupported, setSpeechSupported] = useState(true);
  useEffect(() => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    setSpeechSupported(!!SpeechRecognition);
  }, []);

  // Results state
  const [submitting, setSubmitting] = useState(false);
  const [results, setResults] = useState<any>(null);

  // ── Session persistence: save test progress to sessionStorage ──
  const SESSION_KEY = assessmentId ? `test-progress-${assessmentId}` : null;

  // Restore saved progress on mount
  useEffect(() => {
    if (!SESSION_KEY || typeof window === 'undefined') return;
    try {
      const saved = sessionStorage.getItem(SESSION_KEY);
      if (saved) {
        const state = JSON.parse(saved);
        if (state.grammarAnswers) setGrammarAnswers(state.grammarAnswers);
        if (state.vocabAnswers) setVocabAnswers(state.vocabAnswers);
        if (state.readingAnswers) setReadingAnswers(state.readingAnswers);
        if (state.listeningAnswers) setListeningAnswers(state.listeningAnswers);
        if (state.writingTexts) setWritingTexts(state.writingTexts);
        if (state.speakingTranscript) setSpeakingTranscript(state.speakingTranscript);
        if (state.speakingEvaluations) setSpeakingEvaluations(state.speakingEvaluations);
        if (state.writingEvaluations) setWritingEvaluations(state.writingEvaluations);
        if (state.skillStatuses) setSkillStatuses(state.skillStatuses);
        if (state.phase && state.phase !== 'select') setPhase(state.phase);
        if (state.grammarIdx) setGrammarIdx(state.grammarIdx);
        if (state.vocabIdx) setVocabIdx(state.vocabIdx);
        if (state.readingIdx) setReadingIdx(state.readingIdx);
        if (state.listeningIdx) setListeningIdx(state.listeningIdx);
      }
    } catch {}
  }, [SESSION_KEY]);

  // Save progress to sessionStorage whenever test state changes
  useEffect(() => {
    if (!SESSION_KEY || typeof window === 'undefined' || phase === 'select' || phase === 'results') return;
    try {
      const state = {
        grammarAnswers, vocabAnswers, readingAnswers, listeningAnswers,
        writingTexts, speakingTranscript, speakingEvaluations,
        writingEvaluations, skillStatuses, phase,
        grammarIdx, vocabIdx, readingIdx, listeningIdx,
      };
      sessionStorage.setItem(SESSION_KEY, JSON.stringify(state));
    } catch {}
  }, [SESSION_KEY, grammarAnswers, vocabAnswers, readingAnswers, listeningAnswers,
      writingTexts, speakingTranscript, speakingEvaluations,
      writingEvaluations, skillStatuses, phase,
      grammarIdx, vocabIdx, readingIdx, listeningIdx]);

  // Warn user before leaving/refreshing during an active test + track abandonment
  const isInActiveTest = phase !== 'select' && phase !== 'results';
  useEffect(() => {
    if (!isInActiveTest) return;
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      // Track test abandonment via sendBeacon (reliable during page unload)
      const completedSkills = Object.values(skillStatuses).filter(s => s === 'completed').length;
      const gaId = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID;
      if (gaId && navigator.sendBeacon) {
        const payload = JSON.stringify({
          event_id: crypto.randomUUID(),
          events: [{
            name: 'test_abandon',
            params: {
              step: phase,
              skills_completed: completedSkills,
              skills_total: 6,
              engagement_time_msec: 1,
            },
          }],
        });
        navigator.sendBeacon(
          `https://www.google-analytics.com/g/collect?measurement_id=${gaId}&api_secret=_`,
          payload
        );
      }
      e.preventDefault();
      e.returnValue = 'Your test is in progress. Are you sure you want to leave?';
      return e.returnValue;
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isInActiveTest, phase, skillStatuses]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
      // Cleanup audio
      if (audioRef.current) {
        audioRef.current.pause();
        audioRef.current = null;
      }
      // Revoke all cached blob URLs
      for (const url of audioBlobCache.values()) {
        URL.revokeObjectURL(url);
      }
      audioBlobCache.clear();
      if (recognitionRef.current) {
        try { recognitionRef.current.stop(); } catch {}
      }
    };
  }, []);

  /* ======================================================
     SKILL SELECTION HANDLER
     ====================================================== */
  const startSkill = async (skill: TestPhase) => {
    setPhase(skill);
    setSkillStatuses(prev => ({ ...prev, [skill]: 'in_progress' }));
    // Track test_start on first skill start (when moving from 'select' phase)
    if (skill !== 'select') {
      trackTestStart({ plan: user?.plan, is_resume: resumingAssessment });
    }
  };

  /* ======================================================
     COMPLETE SKILL HELPER
     ====================================================== */
  const completeSkill = (skill: string) => {
    setSkillStatuses(prev => ({ ...prev, [skill]: 'completed' }));
  };

  /* ======================================================
     GRAMMAR LOGIC
     ====================================================== */
  const grammarQuestions = apiQuestions?.grammar || [];
  const currentGrammar = grammarQuestions[grammarIdx];

  const submitGrammar = () => {
    completeSkill('grammar');
    const allDone = Object.values({ ...skillStatuses, grammar: 'completed' }).every(s => s === 'completed');
    if (allDone) {
      submitAssessment();
    } else {
      setPhase('select');
    }
  };

  /* ======================================================
     VOCABULARY LOGIC
     ====================================================== */
  const vocabQuestions = apiQuestions?.vocabulary || [];
  const currentVocab = vocabQuestions[vocabIdx];

  const submitVocabulary = () => {
    completeSkill('vocabulary');
    const allDone = Object.values({ ...skillStatuses, vocabulary: 'completed' }).every(s => s === 'completed');
    if (allDone) {
      submitAssessment();
    } else {
      setPhase('select');
    }
  };

  /* ======================================================
     READING LOGIC
     ====================================================== */
  const readingPassages = apiQuestions?.reading || [];
  const currentReading = readingPassages[readingIdx];

  const submitReading = () => {
    completeSkill('reading');
    const allDone = Object.values({ ...skillStatuses, reading: 'completed' }).every(s => s === 'completed');
    if (allDone) {
      submitAssessment();
    } else {
      setPhase('select');
    }
  };

  /* ======================================================
     LISTENING LOGIC
     ====================================================== */
  const listeningItems = apiQuestions?.listening || [];
  const currentListening = listeningItems[listeningIdx];

  const playAudio = async () => {
    if (isSpeaking || audioLoading || !currentListening) return;

    // Check if audio is already cached — instant replay
    const cachedUrl = audioBlobCache.get(currentListening.id);
    if (cachedUrl) {
      const audio = new Audio(cachedUrl);
      audioRef.current = audio;
      audio.onended = () => setIsSpeaking(false);
      audio.onerror = () => {
        console.error('Audio playback error');
        setIsSpeaking(false);
      };
      setIsSpeaking(true);
      try {
        await audio.play();
      } catch {
        setIsSpeaking(false);
      }
      return;
    }

    // First time — generate natural audio
    setAudioLoading(true);
    try {
      const url = await generateNaturalSpeech(currentListening.id, currentListening.scriptText);
      const audio = new Audio(url);
      audioRef.current = audio;
      audio.onended = () => setIsSpeaking(false);
      audio.onerror = () => {
        console.error('Audio playback error');
        setIsSpeaking(false);
      };
      setIsSpeaking(true);
      setAudioLoading(false);
      await audio.play();
    } catch (e) {
      console.error('[TTS] Failed to generate natural audio:', e);
      setAudioLoading(false);
      // Show error to user — no more browser speechSynthesis fallback (it sounds robotic)
      // The server-side TTS must work; if it fails, show a retry button
      setIsSpeaking(false);
    }
  };

  const stopAudio = () => {
    if (audioRef.current) {
      audioRef.current.pause();
      audioRef.current.currentTime = 0;
      audioRef.current = null;
    }
    // Also stop browser TTS fallback if active
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
    setIsSpeaking(false);
  };

  const submitListening = () => {
    completeSkill('listening');
    const allDone = Object.values({ ...skillStatuses, listening: 'completed' }).every(s => s === 'completed');
    if (allDone) {
      submitAssessment();
    } else {
      setPhase('select');
    }
  };

  /* ======================================================
     SPEAKING LOGIC
     ====================================================== */
  const speakingPrompt = apiQuestions?.speaking || null;

  const startPrepTime = () => {
    if (!speakingPrompt) return;
    setIsPrepTime(true);
    setPrepTimeLeft(speakingPrompt.preparationTime);
    timerRef.current = setInterval(() => {
      setPrepTimeLeft(prev => {
        if (prev <= 1) {
          if (timerRef.current) clearInterval(timerRef.current);
          setIsPrepTime(false);
          startRecording();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
  };

  const startRecording = () => {
    if (!speakingPrompt) return;
    setSpeakingTranscript('');
    setRecordingTime(0);

    // Web Speech API for transcription
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      setSpeechNotSupported(true);
      return;
    }
    setSpeechNotSupported(false);
    const recognition = new SpeechRecognition();
    recognition.continuous = true;
    recognition.interimResults = true;
    recognition.lang = 'en-US';

    let finalTranscript = '';
    recognition.onresult = (event: any) => {
      let interim = '';
      for (let i = event.resultIndex; i < event.results.length; i++) {
        if (event.results[i].isFinal) {
          finalTranscript += event.results[i][0].transcript + ' ';
        } else {
          interim += event.results[i][0].transcript;
        }
      }
      setSpeakingTranscript(finalTranscript + interim);
    };

    recognition.onerror = (event: any) => {
      console.error('Speech recognition error:', event.error);
      if (event.error !== 'no-speech') {
        stopRecording();
      }
    };

    recognitionRef.current = recognition;
    recognition.start();

    setIsRecording(true);
    timerRef.current = setInterval(() => {
      setRecordingTime(prev => {
        if (speakingPrompt && prev >= speakingPrompt.responseTime) {
          stopRecording();
          return prev;
        }
        return prev + 1;
      });
    }, 1000);
  };

  const stopRecording = useCallback(() => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }
    setIsRecording(false);
    setIsPrepTime(false);
    if (recognitionRef.current) {
      try { recognitionRef.current.stop(); } catch {}
    }
  }, []);

  const evaluateSpeaking = async () => {
    if (!speakingTranscript.trim() || !isAuthenticated || !speakingPrompt) return;
    setEvaluatingSpeaking(true);
    try {
      const res = await fetch('/api/assessments/speaking/evaluate/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          transcript: speakingTranscript,
          prompt: speakingPrompt.promptText,
          level: speakingPrompt.level,
        }),
      });
      const data = await res.json();
      if (res.ok) {
        setSpeakingEvaluations(prev => ({ ...prev, [speakingPrompt.id]: data }));
      }
    } catch (e) {
      console.error('Speaking evaluation error:', e);
    } finally {
      setEvaluatingSpeaking(false);
    }
  };

  const submitSpeaking = () => {
    completeSkill('speaking');
    const allDone = Object.values({ ...skillStatuses, speaking: 'completed' }).every(s => s === 'completed');
    if (allDone) {
      submitAssessment();
    } else {
      setPhase('select');
    }
  };

  /* ======================================================
     WRITING LOGIC
     ====================================================== */
  const writingPrompt = apiQuestions?.writing || null;
  const currentWritingText = writingPrompt ? (writingTexts[writingPrompt.id] || '') : '';

  const evaluateWriting = async () => {
    if (!currentWritingText.trim() || !isAuthenticated || !writingPrompt) return;
    setEvaluatingWriting(true);
    try {
      const res = await fetch('/api/assessments/writing/evaluate/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          text: currentWritingText,
          prompt: writingPrompt.promptText,
          level: writingPrompt.level,
        }),
      });
      const data = await res.json();
      if (res.ok) {
        setWritingEvaluations(prev => ({ ...prev, [writingPrompt.id]: data }));
      }
    } catch (e) {
      console.error('Writing evaluation error:', e);
    } finally {
      setEvaluatingWriting(false);
    }
  };

  const submitWriting = () => {
    completeSkill('writing');
    const allDone = Object.values({ ...skillStatuses, writing: 'completed' }).every(s => s === 'completed');
    if (allDone) {
      submitAssessment();
    } else {
      setPhase('select');
    }
  };

  /* ======================================================
     SUBMIT ASSESSMENT
     ====================================================== */
  const submitAssessment = async () => {
    if (!assessmentId || !isAuthenticated) return;
    setSubmitting(true);

    const responses: any[] = [];

    // Grammar responses
    grammarQuestions.forEach(q => {
      const answer = grammarAnswers[q.id];
      responses.push({
        questionId: q.id,
        questionType: 'mcq',
        answer: answer !== undefined ? String(answer) : '',
        level: q.level,
        category: 'grammar',
      });
    });

    // Vocabulary responses
    vocabQuestions.forEach(q => {
      const answer = vocabAnswers[q.id];
      responses.push({
        questionId: q.id,
        questionType: 'mcq',
        answer: answer !== undefined ? String(answer) : '',
        level: q.level,
        category: 'vocabulary',
      });
    });

    // Reading responses
    readingPassages.forEach(passage => {
      passage.questions.forEach(q => {
        const answer = readingAnswers[q.id];
        responses.push({
          questionId: q.id,
          questionType: 'reading',
          parentItemId: passage.id,
          answer: answer !== undefined ? String(answer) : '',
          level: passage.level,
          category: 'reading',
        });
      });
    });

    // Listening responses
    listeningItems.forEach(item => {
      item.questions.forEach(q => {
        const answer = listeningAnswers[q.id];
        responses.push({
          questionId: q.id,
          questionType: 'listening',
          parentItemId: item.id,
          answer: answer !== undefined ? String(answer) : '',
          level: item.level,
          category: 'listening',
        });
      });
    });

    // Speaking response
    if (speakingPrompt) {
      const eval_ = speakingEvaluations[speakingPrompt.id];
      responses.push({
        questionId: speakingPrompt.id,
        questionType: 'speaking',
        answer: speakingTranscript || 'No response',
        level: speakingPrompt.level,
        category: 'speaking',
        aiScore: eval_ ? eval_.score : undefined,
      });
    }

    // Writing response
    if (writingPrompt) {
      const eval_ = writingEvaluations[writingPrompt.id];
      const text = writingTexts[writingPrompt.id] || '';
      responses.push({
        questionId: writingPrompt.id,
        questionType: 'writing',
        answer: text || 'No response',
        level: writingPrompt.level,
        category: 'writing',
        aiScore: eval_ ? eval_.score : undefined,
      });
    }

    try {
      const res = await fetch('/api/assessments/submit/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ assessmentId, responses }),
      });
      const data = await res.json();
      if (res.ok) {
        setResults(data);
        setPhase('results');
        // Track test completion
        trackTestComplete({
          cefr_level: data.cefrLevel || data.overallLevel,
          score: data.overallScore,
          duration_seconds: undefined, // We don't track duration currently
        });
      } else {
        setError(data.message || 'Failed to submit assessment.');
      }
    } catch {
      setError('Failed to submit assessment. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  /* ======================================================
     FORMAT TIME
     ====================================================== */
  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  };

  /* ======================================================
     WORD COUNT
     ====================================================== */
  const wordCount = (text: string) => text.trim().split(/\s+/).filter(Boolean).length;

  /* ======================================================
     LOADING / AUTH GUARD
     ====================================================== */
  if (authIsLoading) {
    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 flex items-center justify-center">
          <Loader2 className="h-8 w-8 text-purple-400 animate-spin" />
        </div>
      </div>
    );
  }

  if (!isAuthenticated || !user) {
    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 flex items-center justify-center px-4 py-12">
          <div className="w-full max-w-md">
            <div className="glass-card p-8 text-center">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-purple-500 to-pink-500 text-white mb-4 shadow-lg shadow-purple-500/25">
                <LogIn className="h-6 w-6" />
              </div>
              <h1 className="text-2xl font-bold text-white mb-2">Sign in to take the test</h1>
              <p className="text-sm text-white/50 mb-6">
                You need to be signed in to start your CEFR assessment.
              </p>
              <Link href="/login">
                <button className="w-full flex items-center justify-center gap-2 rounded-xl py-3 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white font-semibold transition-all duration-300 shadow-lg shadow-purple-500/25 cursor-pointer">
                  <Sparkles className="h-4 w-4" />
                  Sign in
                </button>
              </Link>
              <p className="text-xs text-white/30 mt-4">
                Don&apos;t have an account?{' '}
                <Link href="/register" className="text-purple-400 hover:text-purple-300 transition-colors">
                  Create one
                </Link>
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     LOADING QUESTIONS
     ====================================================== */
  if (isLoadingQuestions) {
    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className="relative mb-6">
              <div className="h-16 w-16 rounded-full border-4 border-purple-500/20 border-t-purple-500 animate-spin mx-auto" />
              <Sparkles className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-6 w-6 text-purple-400" />
            </div>
            <h2 className="text-xl font-semibold text-white mb-2">Preparing Your Assessment</h2>
            <p className="text-sm text-white/50">Selecting questions based on your level...</p>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     NO QUESTIONS FALLBACK
     ====================================================== */
  if (!apiQuestions && !isLoadingQuestions) {
    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 flex items-center justify-center px-4 py-12">
          <div className="w-full max-w-md">
            <div className="glass-card p-8 text-center">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-amber-500 to-orange-500 text-white mb-4">
                <AlertCircle className="h-6 w-6" />
              </div>
              <h1 className="text-xl font-bold text-white mb-2">Unable to Load Questions</h1>
              <p className="text-sm text-white/50 mb-6">
                {error || 'We couldn\'t load the test questions. This may happen if you have an assessment in progress from a previous session. Please refresh the page to try again.'}
              </p>
              <button
                onClick={() => window.location.reload()}
                className="w-full flex items-center justify-center gap-2 rounded-xl py-3 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white font-semibold transition-all duration-300 shadow-lg shadow-purple-500/25 cursor-pointer"
              >
                <RotateCcw className="h-4 w-4" />
                Refresh Page
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     SKILL SELECT PHASE
     ====================================================== */
  if (phase === 'select') {
    const skills = [
      {
        key: 'grammar',
        title: 'Grammar',
        desc: 'Answer multiple-choice questions testing grammar at different CEFR levels.',
        icon: <SpellCheck className="h-7 w-7" />,
        gradient: 'from-rose-500 to-pink-500',
        bgGlow: 'rgba(244,63,94,0.15)',
        levels: 'A2 - C1',
        questions: grammarQuestions.length,
      },
      {
        key: 'vocabulary',
        title: 'Vocabulary',
        desc: 'Answer multiple-choice questions testing vocabulary knowledge at different CEFR levels.',
        icon: <BookMarked className="h-7 w-7" />,
        gradient: 'from-teal-500 to-cyan-500',
        bgGlow: 'rgba(20,184,166,0.15)',
        levels: 'A2 - C1',
        questions: vocabQuestions.length,
      },
      {
        key: 'reading',
        title: 'Reading',
        desc: 'Read passages at different CEFR levels and answer comprehension questions.',
        icon: <BookOpen className="h-7 w-7" />,
        gradient: 'from-blue-500 to-cyan-500',
        bgGlow: 'rgba(59,130,246,0.15)',
        levels: 'B1 - B2',
        questions: readingPassages.length,
      },
      {
        key: 'listening',
        title: 'Listening',
        desc: 'Listen to natural-sounding audio passages and answer questions about what you heard.',
        icon: <Headphones className="h-7 w-7" />,
        gradient: 'from-green-500 to-emerald-500',
        bgGlow: 'rgba(34,197,94,0.15)',
        levels: 'B1 - B2',
        questions: listeningItems.length,
      },
      {
        key: 'speaking',
        title: 'Speaking',
        desc: 'Respond to prompts using your microphone. AI evaluates 6 dimensions of your speech.',
        icon: <Mic className="h-7 w-7" />,
        gradient: 'from-orange-500 to-amber-500',
        bgGlow: 'rgba(249,115,22,0.15)',
        levels: speakingPrompt?.level || 'B2',
        questions: speakingPrompt ? 1 : 0,
      },
      {
        key: 'writing',
        title: 'Writing',
        desc: 'Write responses to prompts at different levels. AI evaluates grammar, vocabulary, coherence, and more.',
        icon: <PenTool className="h-7 w-7" />,
        gradient: 'from-violet-500 to-purple-500',
        bgGlow: 'rgba(139,92,246,0.15)',
        levels: writingPrompt?.level || 'B2',
        questions: writingPrompt ? 1 : 0,
      },
    ];

    const completedCount = Object.values(skillStatuses).filter(s => s === 'completed').length;
    const totalSkills = 6;

    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 py-8 px-4">
          <div className="container max-w-5xl mx-auto">
            {/* Header */}
            <div className="text-center mb-8">
              <div className="inline-flex items-center gap-2 rounded-full glass px-4 py-1.5 mb-4">
                <Sparkles className="h-3.5 w-3.5 text-purple-400" />
                <span className="text-xs text-purple-300 font-medium uppercase tracking-wider">CEFR Assessment</span>
              </div>
              <h1 className="text-3xl md:text-4xl font-bold text-white">
                Take Your <span className="gradient-text-static">CEFR Test</span>
              </h1>
              <p className="mt-3 text-white/50 max-w-xl mx-auto">
                Complete all six skill sections to receive your comprehensive CEFR proficiency score and certificate.
              </p>
            </div>

            {/* Progress */}
            <div className="glass-card p-4 mb-6">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm text-white/60">Progress</span>
                <span className="text-sm font-medium text-white">{completedCount}/{totalSkills} skills completed</span>
              </div>
              <div className="h-2 rounded-full bg-white/5 overflow-hidden">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-purple-500 to-pink-500 transition-all duration-500"
                  style={{ width: `${(completedCount / totalSkills) * 100}%` }}
                />
              </div>
            </div>

            {/* Resume Assessment Banner */}
            {resumingAssessment && (
              <div className="glass-card p-4 mb-6 border-amber-500/30 bg-amber-500/5">
                <div className="flex items-start gap-3">
                  <RotateCcw className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm text-amber-300 font-medium">You have an assessment in progress</p>
                    <p className="text-xs text-white/40 mt-1">
                      It looks like you started a test but didn&apos;t finish. Complete all six skills below to submit your results.
                    </p>
                  </div>
                </div>
              </div>
            )}

            {/* Browser Compatibility Warning for Speaking */}
            {!speechSupported && (
              <div className="glass-card p-4 mb-6 border-amber-500/30 bg-amber-500/5">
                <div className="flex items-start gap-3">
                  <AlertCircle className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm text-amber-300 font-medium">Speaking test requires Chrome</p>
                    <p className="text-xs text-white/40 mt-1">
                      The speaking section uses speech recognition that is only supported in Google Chrome. Please use Chrome for the best experience.
                    </p>
                  </div>
                </div>
              </div>
            )}

            {/* Error */}
            {error && (
              <div className="glass-card p-4 mb-6 border-red-500/30">
                <div className="flex items-start gap-3">
                  <AlertCircle className="h-5 w-5 text-red-400 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm text-red-300">{error}</p>
                    {error.includes('credits') && (
                      <button
                        onClick={() => router.push('/pricing')}
                        className="mt-2 text-sm text-purple-400 hover:text-purple-300 underline cursor-pointer"
                      >
                        Upgrade your plan
                      </button>
                    )}
                  </div>
                </div>
              </div>
            )}

            {/* Skill Cards */}
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {skills.map(skill => {
                const status = skillStatuses[skill.key];
                return (
                  <div
                    key={skill.key}
                    className={`glass-card p-6 cursor-pointer group transition-all duration-300 ${
                      status === 'completed'
                        ? 'border-green-500/30'
                        : skill.questions === 0
                        ? 'opacity-50 cursor-not-allowed'
                        : 'hover:border-purple-500/30'
                    }`}
                    onClick={() => status !== 'completed' && skill.questions > 0 && startSkill(skill.key as TestPhase)}
                  >
                    <div className="flex items-start justify-between mb-4">
                      <div className={`flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br ${skill.gradient} text-white shadow-lg transition-transform duration-300 group-hover:scale-110`}>
                        {skill.icon}
                      </div>
                      {status === 'completed' ? (
                        <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-green-500/20 text-green-400 border border-green-500/30">
                          <CheckCircle2 className="h-3 w-3" /> Completed
                        </span>
                      ) : status === 'in_progress' ? (
                        <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-amber-500/20 text-amber-400 border border-amber-500/30">
                          In Progress
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-white/10 text-white/50 border border-white/10">
                          {skill.levels}
                        </span>
                      )}
                    </div>
                    <h3 className="text-lg font-semibold text-white mb-1">{skill.title}</h3>
                    <p className="text-sm text-white/50 leading-relaxed">{skill.desc}</p>
                    <div className="mt-4 flex items-center justify-between">
                      <span className="text-xs text-white/30">{skill.questions} {skill.key === 'speaking' || skill.key === 'writing' ? 'prompt' : 'questions'}</span>
                      {status !== 'completed' && skill.questions > 0 && (
                        <span className="flex items-center text-sm text-purple-400 font-medium">
                          Start <ArrowRight className="ml-1 h-4 w-4 transition-transform group-hover:translate-x-1" />
                        </span>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Submit All */}
            {completedCount === totalSkills && (
              <div className="mt-6 text-center">
                <button
                  onClick={() => submitAssessment()}
                  disabled={submitting}
                  className="inline-flex items-center gap-2 rounded-xl px-8 py-3.5 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white font-semibold text-base transition-all duration-300 shadow-xl shadow-purple-500/25 hover:shadow-purple-500/40 hover:-translate-y-1 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {submitting ? <Loader2 className="h-5 w-5 animate-spin" /> : <Award className="h-5 w-5" />}
                  {submitting ? 'Submitting...' : 'Submit & Get Results'}
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     GRAMMAR PHASE
     ====================================================== */
  if (phase === 'grammar' && currentGrammar) {
    const answeredCount = Object.keys(grammarAnswers).length;
    const totalQuestions = grammarQuestions.length;

    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 py-8 px-4">
          <div className="container max-w-4xl mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-rose-500 to-pink-500 text-white shadow-lg">
                  <SpellCheck className="h-5 w-5" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-white">Grammar</h2>
                  <p className="text-xs text-white/40">Question {grammarIdx + 1} of {totalQuestions}</p>
                </div>
              </div>
              <span className="inline-flex items-center rounded-full px-3 py-1 text-xs font-bold bg-gradient-to-r from-rose-500/20 to-pink-500/20 text-rose-300 border border-rose-500/30">
                {currentGrammar.level}
              </span>
            </div>

            {/* Progress */}
            <div className="glass-card p-3 mb-6">
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-xs text-white/50">Progress</span>
                <span className="text-xs text-white/70">{answeredCount}/{totalQuestions} answered</span>
              </div>
              <div className="h-1.5 rounded-full bg-white/5 overflow-hidden">
                <div className="h-full rounded-full bg-gradient-to-r from-rose-500 to-pink-500 transition-all" style={{ width: `${(answeredCount / totalQuestions) * 100}%` }} />
              </div>
            </div>

            {/* Question */}
            <div className="glass-card p-6 mb-6">
              <p className="text-white/80 text-[15px] leading-relaxed font-medium mb-4">{currentGrammar.text}</p>
              <div className="space-y-2">
                {currentGrammar.options.map((opt, oi) => {
                  const selected = grammarAnswers[currentGrammar.id];
                  return (
                    <button
                      key={oi}
                      onClick={() => setGrammarAnswers(prev => ({ ...prev, [currentGrammar.id]: oi }))}
                      className={`w-full text-left p-3 rounded-xl text-sm transition-all duration-300 cursor-pointer ${
                        selected === oi
                          ? 'bg-gradient-to-r from-purple-600/30 to-pink-500/30 border border-purple-500/40 text-white'
                          : 'bg-white/5 border border-white/5 text-white/60 hover:bg-white/8 hover:text-white/80'
                      }`}
                    >
                      <span className="font-medium mr-2">{String.fromCharCode(65 + oi)}.</span>
                      {opt}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Navigation */}
            <div className="flex items-center justify-between">
              <button
                onClick={() => setGrammarIdx(Math.max(0, grammarIdx - 1))}
                disabled={grammarIdx === 0}
                className="flex items-center gap-2 rounded-xl px-5 py-2.5 glass-button text-white text-sm font-medium cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <ChevronLeft className="h-4 w-4" /> Previous
              </button>
              {grammarIdx < totalQuestions - 1 ? (
                <button
                  onClick={() => setGrammarIdx(grammarIdx + 1)}
                  className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white text-sm font-medium transition-all shadow-lg shadow-purple-500/25 cursor-pointer"
                >
                  Next <ChevronRight className="h-4 w-4" />
                </button>
              ) : (
                <button
                  onClick={submitGrammar}
                  className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-green-600 to-emerald-500 hover:from-green-500 hover:to-emerald-400 text-white text-sm font-medium transition-all shadow-lg cursor-pointer"
                >
                  <CheckCircle2 className="h-4 w-4" /> Complete Grammar
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     VOCABULARY PHASE
     ====================================================== */
  if (phase === 'vocabulary' && currentVocab) {
    const answeredCount = Object.keys(vocabAnswers).length;
    const totalQuestions = vocabQuestions.length;

    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 py-8 px-4">
          <div className="container max-w-4xl mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-teal-500 to-cyan-500 text-white shadow-lg">
                  <BookMarked className="h-5 w-5" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-white">Vocabulary</h2>
                  <p className="text-xs text-white/40">Question {vocabIdx + 1} of {totalQuestions}</p>
                </div>
              </div>
              <span className="inline-flex items-center rounded-full px-3 py-1 text-xs font-bold bg-gradient-to-r from-teal-500/20 to-cyan-500/20 text-teal-300 border border-teal-500/30">
                {currentVocab.level}
              </span>
            </div>

            {/* Progress */}
            <div className="glass-card p-3 mb-6">
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-xs text-white/50">Progress</span>
                <span className="text-xs text-white/70">{answeredCount}/{totalQuestions} answered</span>
              </div>
              <div className="h-1.5 rounded-full bg-white/5 overflow-hidden">
                <div className="h-full rounded-full bg-gradient-to-r from-teal-500 to-cyan-500 transition-all" style={{ width: `${(answeredCount / totalQuestions) * 100}%` }} />
              </div>
            </div>

            {/* Question */}
            <div className="glass-card p-6 mb-6">
              <p className="text-white/80 text-[15px] leading-relaxed font-medium mb-4">{currentVocab.text}</p>
              <div className="space-y-2">
                {currentVocab.options.map((opt, oi) => {
                  const selected = vocabAnswers[currentVocab.id];
                  return (
                    <button
                      key={oi}
                      onClick={() => setVocabAnswers(prev => ({ ...prev, [currentVocab.id]: oi }))}
                      className={`w-full text-left p-3 rounded-xl text-sm transition-all duration-300 cursor-pointer ${
                        selected === oi
                          ? 'bg-gradient-to-r from-purple-600/30 to-pink-500/30 border border-purple-500/40 text-white'
                          : 'bg-white/5 border border-white/5 text-white/60 hover:bg-white/8 hover:text-white/80'
                      }`}
                    >
                      <span className="font-medium mr-2">{String.fromCharCode(65 + oi)}.</span>
                      {opt}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Navigation */}
            <div className="flex items-center justify-between">
              <button
                onClick={() => setVocabIdx(Math.max(0, vocabIdx - 1))}
                disabled={vocabIdx === 0}
                className="flex items-center gap-2 rounded-xl px-5 py-2.5 glass-button text-white text-sm font-medium cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <ChevronLeft className="h-4 w-4" /> Previous
              </button>
              {vocabIdx < totalQuestions - 1 ? (
                <button
                  onClick={() => setVocabIdx(vocabIdx + 1)}
                  className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white text-sm font-medium transition-all shadow-lg shadow-purple-500/25 cursor-pointer"
                >
                  Next <ChevronRight className="h-4 w-4" />
                </button>
              ) : (
                <button
                  onClick={submitVocabulary}
                  className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-green-600 to-emerald-500 hover:from-green-500 hover:to-emerald-400 text-white text-sm font-medium transition-all shadow-lg cursor-pointer"
                >
                  <CheckCircle2 className="h-4 w-4" /> Complete Vocabulary
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     READING PHASE
     ====================================================== */
  if (phase === 'reading' && currentReading) {
    const totalQuestions = readingPassages.reduce((sum, p) => sum + p.questions.length, 0);
    const answeredCount = Object.keys(readingAnswers).length;

    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 py-8 px-4">
          <div className="container max-w-4xl mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 text-white shadow-lg">
                  <BookOpen className="h-5 w-5" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-white">Reading Comprehension</h2>
                  <p className="text-xs text-white/40">Passage {readingIdx + 1} of {readingPassages.length}</p>
                </div>
              </div>
              <span className="inline-flex items-center rounded-full px-3 py-1 text-xs font-bold bg-gradient-to-r from-blue-500/20 to-cyan-500/20 text-blue-300 border border-blue-500/30">
                {currentReading.level}
              </span>
            </div>

            {/* Progress */}
            <div className="glass-card p-3 mb-6">
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-xs text-white/50">Progress</span>
                <span className="text-xs text-white/70">{answeredCount}/{totalQuestions} answered</span>
              </div>
              <div className="h-1.5 rounded-full bg-white/5 overflow-hidden">
                <div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-500 transition-all" style={{ width: `${(answeredCount / totalQuestions) * 100}%` }} />
              </div>
            </div>

            {/* Passage */}
            <div className="glass-card p-6 mb-6">
              {currentReading.title && (
                <p className="text-sm font-semibold text-white/60 mb-3">{currentReading.title}</p>
              )}
              <p className="text-xs text-white/40 uppercase tracking-wider mb-3">Read the passage carefully</p>
              <p className="text-white/80 leading-relaxed text-[15px]">{currentReading.passageText}</p>
            </div>

            {/* Questions */}
            <div className="space-y-4 mb-6">
              {currentReading.questions.map((q, qi) => {
                const selected = readingAnswers[q.id];
                return (
                  <div key={q.id} className="glass-card p-5">
                    <p className="text-sm font-medium text-white mb-3">{qi + 1}. {q.questionText}</p>
                    <div className="space-y-2">
                      {q.options.map((opt, oi) => (
                        <button
                          key={oi}
                          onClick={() => setReadingAnswers(prev => ({ ...prev, [q.id]: oi }))}
                          className={`w-full text-left p-3 rounded-xl text-sm transition-all duration-300 cursor-pointer ${
                            selected === oi
                              ? 'bg-gradient-to-r from-purple-600/30 to-pink-500/30 border border-purple-500/40 text-white'
                              : 'bg-white/5 border border-white/5 text-white/60 hover:bg-white/8 hover:text-white/80'
                          }`}
                        >
                          <span className="font-medium mr-2">{String.fromCharCode(65 + oi)}.</span>
                          {opt}
                        </button>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Navigation */}
            <div className="flex items-center justify-between">
              <button
                onClick={() => setReadingIdx(Math.max(0, readingIdx - 1))}
                disabled={readingIdx === 0}
                className="flex items-center gap-2 rounded-xl px-5 py-2.5 glass-button text-white text-sm font-medium cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <ChevronLeft className="h-4 w-4" /> Previous
              </button>
              {readingIdx < readingPassages.length - 1 ? (
                <button
                  onClick={() => setReadingIdx(readingIdx + 1)}
                  className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white text-sm font-medium transition-all shadow-lg shadow-purple-500/25 cursor-pointer"
                >
                  Next <ChevronRight className="h-4 w-4" />
                </button>
              ) : (
                <button
                  onClick={submitReading}
                  className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-green-600 to-emerald-500 hover:from-green-500 hover:to-emerald-400 text-white text-sm font-medium transition-all shadow-lg cursor-pointer"
                >
                  <CheckCircle2 className="h-4 w-4" /> Complete Reading
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     LISTENING PHASE
     ====================================================== */
  if (phase === 'listening' && currentListening) {
    const totalQuestions = listeningItems.reduce((sum, item) => sum + item.questions.length, 0);
    const answeredCount = Object.keys(listeningAnswers).length;

    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 py-8 px-4">
          <div className="container max-w-4xl mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-green-500 to-emerald-500 text-white shadow-lg">
                  <Headphones className="h-5 w-5" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-white">Listening Comprehension</h2>
                  <p className="text-xs text-white/40">Audio {listeningIdx + 1} of {listeningItems.length}</p>
                </div>
              </div>
              <span className="inline-flex items-center rounded-full px-3 py-1 text-xs font-bold bg-gradient-to-r from-green-500/20 to-emerald-500/20 text-green-300 border border-green-500/30">
                {currentListening.level}
              </span>
            </div>

            {/* Progress */}
            <div className="glass-card p-3 mb-6">
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-xs text-white/50">Progress</span>
                <span className="text-xs text-white/70">{answeredCount}/{totalQuestions} answered</span>
              </div>
              <div className="h-1.5 rounded-full bg-white/5 overflow-hidden">
                <div className="h-full rounded-full bg-gradient-to-r from-green-500 to-emerald-500 transition-all" style={{ width: `${(answeredCount / totalQuestions) * 100}%` }} />
              </div>
            </div>

            {/* Audio Player */}
            <div className="glass-card p-6 mb-6">
              <p className="text-xs text-white/40 uppercase tracking-wider mb-3">Listen to the audio</p>
              <div className="flex items-center gap-4">
                <button
                  onClick={isSpeaking ? stopAudio : playAudio}
                  disabled={audioLoading}
                  className={`flex h-14 w-14 items-center justify-center rounded-full transition-all duration-300 cursor-pointer disabled:cursor-wait ${
                    audioLoading
                      ? 'bg-gradient-to-br from-purple-500 to-purple-600 shadow-2xl shadow-purple-500/40'
                      : isSpeaking
                      ? 'bg-gradient-to-br from-red-500 to-red-600 shadow-2xl shadow-red-500/40 animate-pulse'
                      : 'bg-gradient-to-br from-green-500 to-emerald-500 shadow-2xl shadow-green-500/40 hover:scale-110'
                  }`}
                >
                  {audioLoading ? (
                    <Loader2 className="h-6 w-6 text-white animate-spin" />
                  ) : isSpeaking ? (
                    <Square className="h-6 w-6 text-white" />
                  ) : (
                    <Play className="h-6 w-6 text-white ml-1" />
                  )}
                </button>
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    {audioLoading ? (
                      <span className="text-sm text-purple-300 font-medium flex items-center gap-1">
                        <Loader2 className="h-4 w-4 animate-spin" /> Generating natural audio...
                      </span>
                    ) : isSpeaking ? (
                      <span className="text-sm text-green-300 font-medium flex items-center gap-1">
                        <Volume2 className="h-4 w-4" /> Playing audio...
                      </span>
                    ) : (
                      <span className="text-sm text-white/50 flex items-center gap-1">
                        <VolumeX className="h-4 w-4" /> Click play to listen
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-white/30 mt-1">You can play the audio multiple times</p>
                </div>
              </div>

              {/* Transcript (hidden by default, can toggle) */}
              <details className="mt-4">
                <summary className="text-xs text-white/30 cursor-pointer hover:text-white/50 transition-colors">
                  Show transcript (for accessibility)
                </summary>
                <p className="mt-2 text-sm text-white/50 italic leading-relaxed">{currentListening.scriptText}</p>
              </details>
            </div>

            {/* Questions */}
            <div className="space-y-4 mb-6">
              {currentListening.questions.map((q, qi) => {
                const selected = listeningAnswers[q.id];
                return (
                  <div key={q.id} className="glass-card p-5">
                    <p className="text-sm font-medium text-white mb-3">{qi + 1}. {q.questionText}</p>
                    <div className="space-y-2">
                      {q.options.map((opt, oi) => (
                        <button
                          key={oi}
                          onClick={() => setListeningAnswers(prev => ({ ...prev, [q.id]: oi }))}
                          className={`w-full text-left p-3 rounded-xl text-sm transition-all duration-300 cursor-pointer ${
                            selected === oi
                              ? 'bg-gradient-to-r from-purple-600/30 to-pink-500/30 border border-purple-500/40 text-white'
                              : 'bg-white/5 border border-white/5 text-white/60 hover:bg-white/8 hover:text-white/80'
                          }`}
                        >
                          <span className="font-medium mr-2">{String.fromCharCode(65 + oi)}.</span>
                          {opt}
                        </button>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Navigation */}
            <div className="flex items-center justify-between">
              <button
                onClick={() => setListeningIdx(Math.max(0, listeningIdx - 1))}
                disabled={listeningIdx === 0}
                className="flex items-center gap-2 rounded-xl px-5 py-2.5 glass-button text-white text-sm font-medium cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <ChevronLeft className="h-4 w-4" /> Previous
              </button>
              {listeningIdx < listeningItems.length - 1 ? (
                <button
                  onClick={() => setListeningIdx(listeningIdx + 1)}
                  className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white text-sm font-medium transition-all shadow-lg shadow-purple-500/25 cursor-pointer"
                >
                  Next <ChevronRight className="h-4 w-4" />
                </button>
              ) : (
                <button
                  onClick={submitListening}
                  className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-green-600 to-emerald-500 hover:from-green-500 hover:to-emerald-400 text-white text-sm font-medium transition-all shadow-lg cursor-pointer"
                >
                  <CheckCircle2 className="h-4 w-4" /> Complete Listening
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     SPEAKING PHASE
     ====================================================== */
  if (phase === 'speaking' && speakingPrompt) {
    const hasEvaluation = !!speakingEvaluations[speakingPrompt.id];
    const evaluation = speakingEvaluations[speakingPrompt.id];
    const dimensions = evaluation?.dimensions
      ? [
          { key: 'grammar', label: 'Grammar (G)', ...evaluation.dimensions.grammar, color: 'from-purple-500 to-violet-500' },
          { key: 'vocabulary', label: 'Vocabulary (V)', ...evaluation.dimensions.vocabulary, color: 'from-pink-500 to-rose-500' },
          { key: 'fluency', label: 'Fluency (F)', ...evaluation.dimensions.fluency, color: 'from-blue-500 to-cyan-500' },
          { key: 'pronunciation', label: 'Pronunciation (P)', ...evaluation.dimensions.pronunciation, color: 'from-green-500 to-emerald-500' },
          { key: 'coherence', label: 'Coherence (C)', ...evaluation.dimensions.coherence, color: 'from-orange-500 to-amber-500' },
          { key: 'interaction', label: 'Interaction (I)', ...evaluation.dimensions.interaction, color: 'from-red-500 to-pink-500' },
        ]
      : [];

    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 py-8 px-4">
          <div className="container max-w-4xl mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-orange-500 to-amber-500 text-white shadow-lg">
                  <Mic className="h-5 w-5" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-white">Speaking Assessment</h2>
                  <p className="text-xs text-white/40">1 prompt</p>
                </div>
              </div>
              <span className="inline-flex items-center rounded-full px-3 py-1 text-xs font-bold bg-gradient-to-r from-orange-500/20 to-amber-500/20 text-orange-300 border border-orange-500/30">
                {speakingPrompt.level}
              </span>
            </div>

            {/* Prompt */}
            <div className="glass-card p-6 mb-6">
              <p className="text-xs text-white/40 uppercase tracking-wider mb-2">Speaking Prompt</p>
              <p className="text-white/80 text-[15px] leading-relaxed italic">&ldquo;{speakingPrompt.promptText}&rdquo;</p>
              <div className="flex gap-4 mt-3">
                <span className="text-xs text-white/30">Prep: {speakingPrompt.preparationTime}s</span>
                <span className="text-xs text-white/30">Response: {speakingPrompt.responseTime}s</span>
              </div>
            </div>

            {/* Mic Controls */}
            {!hasEvaluation ? (
              <div className="glass-card p-6 mb-6">
                {speechNotSupported && (
                  <div className="mb-6 p-4 rounded-xl bg-amber-500/10 border border-amber-500/30">
                    <div className="flex items-start gap-3">
                      <AlertCircle className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
                      <div>
                        <p className="text-amber-300 font-semibold text-sm">Browser Not Supported</p>
                        <p className="text-white/60 text-xs mt-1">Your browser does not support speech recognition. Please use <strong>Google Chrome</strong> or <strong>Microsoft Edge</strong> for the speaking assessment, or skip to the next section.</p>
                      </div>
                    </div>
                  </div>
                )}
                <div className="flex flex-col items-center">
                  {/* Status */}
                  <div className="flex items-center gap-2 mb-6">
                    {isRecording ? (
                      <>
                        <span className="w-2.5 h-2.5 rounded-full bg-red-400 animate-pulse" />
                        <span className="text-sm text-red-300 font-medium">RECORDING</span>
                        <span className="text-sm text-white/50 ml-2">{formatTime(recordingTime)} / {formatTime(speakingPrompt.responseTime)}</span>
                      </>
                    ) : isPrepTime ? (
                      <>
                        <Clock className="h-4 w-4 text-amber-400" />
                        <span className="text-sm text-amber-300 font-medium">PREPARATION TIME</span>
                        <span className="text-sm text-white/50 ml-2">{prepTimeLeft}s remaining</span>
                      </>
                    ) : (
                      <>
                        <span className="w-2.5 h-2.5 rounded-full bg-green-400" />
                        <span className="text-sm text-green-300 font-medium">READY</span>
                      </>
                    )}
                  </div>

                  {/* Waveform visualization */}
                  <div className="flex items-center justify-center gap-[3px] h-12 mb-6">
                    {Array.from({ length: 24 }).map((_, i) => (
                      <div
                        key={i}
                        className={`waveform-bar ${isRecording ? (i % 2 === 0 ? 'active' : 'waveform-bar-alt active') : ''}`}
                        style={{
                          height: isRecording ? undefined : `${6 + Math.sin(i * 0.5) * 4 + 4}px`,
                          animationDelay: `${i * 0.06}s`,
                          opacity: isRecording ? 1 : 0.25,
                        }}
                      />
                    ))}
                  </div>

                  {/* Mic button */}
                  <div className="relative mb-6">
                    {isRecording && (
                      <>
                        <div className="absolute inset-[-8px] rounded-full border-2 border-red-400/30 animate-ripple" />
                        <div className="absolute inset-[-8px] rounded-full border-2 border-red-400/20 animate-ripple" style={{ animationDelay: '0.5s' }} />
                      </>
                    )}
                    <div className={`absolute -inset-6 rounded-full transition-all duration-500 ${isRecording ? 'bg-red-500/15 blur-2xl' : 'bg-purple-500/15 blur-2xl'}`} />
                    <button
                      onClick={() => {
                        if (isRecording) {
                          stopRecording();
                        } else if (!isPrepTime) {
                          startPrepTime();
                        }
                      }}
                      disabled={isPrepTime}
                      className={`relative w-20 h-20 rounded-full flex items-center justify-center transition-all duration-300 cursor-pointer disabled:cursor-not-allowed ${
                        isRecording
                          ? 'bg-gradient-to-br from-red-500 to-red-600 shadow-2xl shadow-red-500/40 animate-recording-pulse'
                          : isPrepTime
                          ? 'bg-gradient-to-br from-amber-500 to-amber-600 shadow-2xl shadow-amber-500/40'
                          : 'bg-gradient-to-br from-purple-500 to-pink-500 shadow-2xl shadow-purple-500/40 hover:shadow-purple-500/60 hover:scale-110 animate-mic-glow'
                      }`}
                    >
                      {isRecording ? (
                        <Square className="h-8 w-8 text-white" />
                      ) : isPrepTime ? (
                        <Clock className="h-8 w-8 text-white animate-pulse" />
                      ) : (
                        <Mic className="h-8 w-8 text-white" />
                      )}
                    </button>
                  </div>

                  {/* Transcript */}
                  {speakingTranscript && (
                    <div className="w-full mb-4">
                      <p className="text-xs text-white/40 uppercase tracking-wider mb-2">Your Response (Live)</p>
                      <div className="glass-card p-4">
                        <p className="text-sm text-white/70 leading-relaxed">{speakingTranscript}</p>
                      </div>
                    </div>
                  )}

                  <p className="text-xs text-white/30 text-center">
                    {isPrepTime
                      ? 'Get ready to speak when the timer runs out...'
                      : isRecording
                      ? 'Click stop when you are done speaking'
                      : 'Click the microphone to start (prep time included)'}
                  </p>

                  {/* Evaluate button */}
                  {speakingTranscript && !isRecording && !isPrepTime && (
                    <button
                      onClick={evaluateSpeaking}
                      disabled={evaluatingSpeaking}
                      className="mt-4 flex items-center gap-2 rounded-xl px-6 py-2.5 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white text-sm font-medium transition-all shadow-lg cursor-pointer disabled:opacity-50"
                    >
                      {evaluatingSpeaking ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
                      {evaluatingSpeaking ? 'Evaluating...' : 'Evaluate Response'}
                    </button>
                  )}
                </div>
              </div>
            ) : (
              /* Evaluation Results */
              <div className="glass-card p-6 mb-6">
                <div className="flex items-center gap-2 mb-4">
                  <Award className="h-5 w-5 text-purple-400" />
                  <h3 className="text-lg font-semibold text-white">Speaking Evaluation</h3>
                  <span className="ml-auto inline-flex items-center rounded-full px-3 py-1 text-xs font-bold bg-gradient-to-r from-purple-500/20 to-pink-500/20 text-purple-300 border border-purple-500/30">
                    {evaluation!.cefrLevel} - Score: {evaluation!.score}/100
                  </span>
                </div>

                <p className="text-sm text-white/60 mb-4">{evaluation!.feedback}</p>

                {/* 6 Dimensions */}
                <div className="grid gap-3 sm:grid-cols-2 mb-4">
                  {dimensions.map(dim => (
                    <div key={dim.key} className="glass-card p-3">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-white">{dim.label}</span>
                        <span className="text-sm font-bold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
                          {dim.score}/100
                        </span>
                      </div>
                      <div className="h-1.5 rounded-full bg-white/5 overflow-hidden">
                        <div
                          className={`h-full rounded-full bg-gradient-to-r ${dim.color} transition-all duration-1000`}
                          style={{ width: `${dim.score}%` }}
                        />
                      </div>
                      <p className="text-xs text-white/40 mt-1">{dim.feedback}</p>
                    </div>
                  ))}
                </div>

                {/* Strengths & Improvements */}
                <div className="grid gap-3 sm:grid-cols-2">
                  {evaluation!.strengths.length > 0 && (
                    <div>
                      <p className="text-xs text-green-400 uppercase tracking-wider mb-2">Strengths</p>
                      {evaluation!.strengths.map((s, i) => (
                        <div key={i} className="flex items-start gap-2 mb-1">
                          <CheckCircle2 className="h-3.5 w-3.5 text-green-400 shrink-0 mt-0.5" />
                          <span className="text-xs text-white/60">{s}</span>
                        </div>
                      ))}
                    </div>
                  )}
                  {evaluation!.improvements.length > 0 && (
                    <div>
                      <p className="text-xs text-amber-400 uppercase tracking-wider mb-2">Improvements</p>
                      {evaluation!.improvements.map((s, i) => (
                        <div key={i} className="flex items-start gap-2 mb-1">
                          <AlertCircle className="h-3.5 w-3.5 text-amber-400 shrink-0 mt-0.5" />
                          <span className="text-xs text-white/60">{s}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Complete Speaking */}
            <div className="flex justify-end">
              <button
                onClick={submitSpeaking}
                className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-green-600 to-emerald-500 hover:from-green-500 hover:to-emerald-400 text-white text-sm font-medium transition-all shadow-lg cursor-pointer"
              >
                <CheckCircle2 className="h-4 w-4" /> Complete Speaking
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     WRITING PHASE
     ====================================================== */
  if (phase === 'writing' && writingPrompt) {
    const wc = wordCount(currentWritingText);
    const hasEvaluation = !!writingEvaluations[writingPrompt.id];
    const evaluation = writingEvaluations[writingPrompt.id];

    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 py-8 px-4">
          <div className="container max-w-4xl mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500 to-purple-500 text-white shadow-lg">
                  <PenTool className="h-5 w-5" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-white">Writing Assessment</h2>
                  <p className="text-xs text-white/40">1 prompt</p>
                </div>
              </div>
              <span className="inline-flex items-center rounded-full px-3 py-1 text-xs font-bold bg-gradient-to-r from-violet-500/20 to-purple-500/20 text-violet-300 border border-violet-500/30">
                {writingPrompt.level}
              </span>
            </div>

            {/* Prompt */}
            <div className="glass-card p-6 mb-6">
              <p className="text-xs text-white/40 uppercase tracking-wider mb-2">Writing Prompt</p>
              <p className="text-white/80 text-[15px] leading-relaxed">{writingPrompt.promptText}</p>
              <p className="text-xs text-white/30 mt-3">
                Suggested word count: {writingPrompt.minWords} - {writingPrompt.maxWords} words
              </p>
            </div>

            {/* Writing Area */}
            {!hasEvaluation ? (
              <div className="glass-card p-6 mb-6">
                <div className="flex items-center justify-between mb-3">
                  <p className="text-xs text-white/40 uppercase tracking-wider">Your Response</p>
                  <span className={`text-xs font-medium ${wc < writingPrompt.minWords ? 'text-amber-400' : wc > writingPrompt.maxWords ? 'text-red-400' : 'text-green-400'}`}>
                    {wc} words
                  </span>
                </div>
                <textarea
                  value={currentWritingText}
                  onChange={(e) => setWritingTexts(prev => ({ ...prev, [writingPrompt.id]: e.target.value }))}
                  placeholder="Start writing your response here..."
                  className="w-full h-64 bg-white/5 border border-white/10 rounded-xl p-4 text-white/80 text-sm leading-relaxed placeholder-white/20 focus:outline-none focus:border-purple-500/40 focus:ring-2 focus:ring-purple-500/20 transition-all resize-none"
                />
                <div className="mt-4 flex justify-end">
                  <button
                    onClick={evaluateWriting}
                    disabled={evaluatingWriting || wc < 10}
                    className="flex items-center gap-2 rounded-xl px-6 py-2.5 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white text-sm font-medium transition-all shadow-lg cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {evaluatingWriting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
                    {evaluatingWriting ? 'Evaluating...' : 'Evaluate Writing'}
                  </button>
                </div>
              </div>
            ) : (
              /* Writing Evaluation */
              <div className="glass-card p-6 mb-6">
                <div className="flex items-center gap-2 mb-4">
                  <Award className="h-5 w-5 text-purple-400" />
                  <h3 className="text-lg font-semibold text-white">Writing Evaluation</h3>
                  <span className="ml-auto inline-flex items-center rounded-full px-3 py-1 text-xs font-bold bg-gradient-to-r from-violet-500/20 to-purple-500/20 text-violet-300 border border-violet-500/30">
                    {evaluation!.cefrLevel} - Score: {evaluation!.score}/100
                  </span>
                </div>

                <p className="text-sm text-white/60 mb-4">{evaluation!.feedback}</p>

                <div className="grid gap-3 sm:grid-cols-2 mb-4">
                  {evaluation!.strengths.length > 0 && (
                    <div>
                      <p className="text-xs text-green-400 uppercase tracking-wider mb-2">Strengths</p>
                      {evaluation!.strengths.map((s, i) => (
                        <div key={i} className="flex items-start gap-2 mb-1">
                          <CheckCircle2 className="h-3.5 w-3.5 text-green-400 shrink-0 mt-0.5" />
                          <span className="text-xs text-white/60">{s}</span>
                        </div>
                      ))}
                    </div>
                  )}
                  {evaluation!.improvements.length > 0 && (
                    <div>
                      <p className="text-xs text-amber-400 uppercase tracking-wider mb-2">Improvements</p>
                      {evaluation!.improvements.map((s, i) => (
                        <div key={i} className="flex items-start gap-2 mb-1">
                          <AlertCircle className="h-3.5 w-3.5 text-amber-400 shrink-0 mt-0.5" />
                          <span className="text-xs text-white/60">{s}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Show the written text */}
                <div>
                  <p className="text-xs text-white/40 uppercase tracking-wider mb-2">Your Response</p>
                  <div className="bg-white/5 rounded-xl p-4">
                    <p className="text-sm text-white/60 leading-relaxed">{currentWritingText}</p>
                  </div>
                </div>
              </div>
            )}

            {/* Complete Writing */}
            <div className="flex justify-end">
              <button
                onClick={submitWriting}
                className="flex items-center gap-2 rounded-xl px-5 py-2.5 bg-gradient-to-r from-green-600 to-emerald-500 hover:from-green-500 hover:to-emerald-400 text-white text-sm font-medium transition-all shadow-lg cursor-pointer"
              >
                <CheckCircle2 className="h-4 w-4" /> Complete Writing
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     RESULTS PHASE
     ====================================================== */
  if (phase === 'results' && results) {
    const cefrGradients: Record<string, string> = {
      A1: 'from-blue-400 to-blue-600',
      A2: 'from-green-400 to-green-600',
      B1: 'from-yellow-400 to-yellow-600',
      B2: 'from-orange-400 to-orange-600',
      C1: 'from-red-400 to-red-600',
      C2: 'from-purple-400 to-purple-600',
    };

    return (
      <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
        <Navbar />
        <div className="flex-1 py-8 px-4">
          <div className="container max-w-4xl mx-auto">
            {/* Header */}
            <div className="text-center mb-8">
              <div className="inline-flex items-center gap-2 rounded-full glass px-4 py-1.5 mb-4">
                <Award className="h-3.5 w-3.5 text-purple-400" />
                <span className="text-xs text-purple-300 font-medium uppercase tracking-wider">Assessment Complete</span>
              </div>
              <h1 className="text-3xl md:text-4xl font-bold text-white">
                Your <span className="gradient-text-static">CEFR Results</span>
              </h1>
            </div>

            {/* Main Result */}
            <div className="glass-card-neon p-8 mb-6 text-center">
              <div className={`inline-flex items-center justify-center h-24 w-24 rounded-2xl bg-gradient-to-br ${cefrGradients[results.assessment.cefrLevel] || 'from-purple-400 to-purple-600'} text-white text-4xl font-black shadow-2xl mb-4`}>
                {results.assessment.cefrLevel}
              </div>
              <h2 className="text-2xl font-bold text-white mb-2">CEFR Level: {results.assessment.cefrLevel}</h2>
              <p className="text-lg text-white/60">Overall Score: {results.assessment.score}/100</p>

              <div className="grid grid-cols-3 gap-4 mt-6">
                <div className="glass-card p-4">
                  <p className="text-2xl font-bold text-white">{results.results.correctCount}</p>
                  <p className="text-xs text-white/40">Correct</p>
                </div>
                <div className="glass-card p-4">
                  <p className="text-2xl font-bold text-white">{results.results.totalQuestions}</p>
                  <p className="text-xs text-white/40">Total Questions</p>
                </div>
                <div className="glass-card p-4">
                  <p className="text-2xl font-bold text-white">{results.results.percentage}%</p>
                  <p className="text-xs text-white/40">Accuracy</p>
                </div>
              </div>
            </div>

            {/* Certificate */}
            {results.certificate && (
              <div className="glass-card p-6 mb-6">
                <div className="flex items-center gap-3 mb-4">
                  <Award className="h-5 w-5 text-purple-400" />
                  <h3 className="text-lg font-semibold text-white">Your Certificate</h3>
                </div>
                <div className="flex items-center justify-between p-4 rounded-xl bg-white/5">
                  <div>
                    <p className="font-medium text-white">CEFR {results.certificate.cefrLevel} Certificate</p>
                    <p className="text-xs text-white/40">Score: {results.certificate.score}/100 | ID: {results.certificate.verificationId}</p>
                  </div>
                  <a href={`/api/certificates/download/${results.certificate.verificationId}`} target="_blank" rel="noopener noreferrer">
                    <button className="flex items-center gap-1 rounded-lg px-4 py-2 text-xs font-medium bg-gradient-to-r from-purple-600 to-pink-500 text-white shadow-lg cursor-pointer">
                      Download PDF
                    </button>
                  </a>
                </div>
              </div>
            )}

            {/* Message */}
            <div className="glass-card p-6 mb-6">
              <p className="text-sm text-white/60 text-center">{results.message}</p>
            </div>

            {/* Actions */}
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <button
                onClick={() => router.push('/dashboard')}
                className="flex items-center justify-center gap-2 rounded-xl px-6 py-3 glass-button text-white font-medium cursor-pointer"
              >
                Go to Dashboard
              </button>
              <button
                onClick={() => {
                  setPhase('select');
                  setAssessmentId(null);
                  setApiQuestions(null);
                  setSkillStatuses({ grammar: 'pending', vocabulary: 'pending', reading: 'pending', listening: 'pending', speaking: 'pending', writing: 'pending' });
                  setGrammarIdx(0);
                  setVocabIdx(0);
                  setReadingIdx(0);
                  setListeningIdx(0);
                  setGrammarAnswers({});
                  setVocabAnswers({});
                  setReadingAnswers({});
                  setListeningAnswers({});
                  setSpeakingTranscript('');
                  setSpeakingEvaluations({});
                  setWritingTexts({});
                  setWritingEvaluations({});
                  setResults(null);
                  setError(null);
                  setIsLoadingQuestions(true);
                  // Re-fetch questions
                  fetch('/api/assessments/start/', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                  }).then(res => res.json()).then(data => {
                    if (data.assessment) setAssessmentId(data.assessment.id);
                    if (data.questions) setApiQuestions(data.questions);
                  }).catch(() => {}).finally(() => setIsLoadingQuestions(false));
                }}
                className="flex items-center justify-center gap-2 rounded-xl px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-500 hover:from-purple-500 hover:to-pink-400 text-white font-medium transition-all shadow-lg cursor-pointer"
              >
                <RotateCcw className="h-4 w-4" /> Retake Test
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ======================================================
     FALLBACK - LOADING
     ====================================================== */
  return (
    <div className="min-h-screen flex flex-col bg-[#0F0A1E]">
      <Navbar />
      <div className="flex-1 flex items-center justify-center">
        <Loader2 className="h-8 w-8 text-purple-400 animate-spin" />
      </div>
    </div>
  );
}
